### ISSUE TITLE
Archive email shortcut

### ISSUE THREAD

**Issue by adrianroth10** [LukeSmithxyz/mutt-wizard#102]
I'm interested in a command to archive the email directly. Without writing M, choosing mailbox and verify that I want to append. Is it possible to add something like:
`macro index,pager - "<save-message>=Archive<enter><enter>" "Archive"`

Not sure if the shortcut '-' is the best choice and maybe the Archive is not available for all email providers but can you maybe add it during the 'Redetect mailboxes' if an Archive folder is found.

What do you think?

**Comment by LukeSmithxyz** [comment]
Why not `A`? J I don't think it's bound to anything. Just `D` is delete; makes sense to me.

Yeah the proper place to add it would be on the redetect command just because some providers might have it named something a little bit different: i.e. my archive folder has the year in it, or others might have it all lowercase or capital or something.

If you submit a PR adding it I'll merge it.

**Comment by adrianroth10** [comment]
It seems that A is bound to
`macro index A "<limit>all\n" "show all messages (undo limit)"`
Should I still use A?
