### ISSUE TITLE
Is it possible to configure my university email?

### ISSUE THREAD

**Issue by emorevival** [LukeSmithxyz/mutt-wizard#119]
I want to configure my university mail with mutt-wizard, our emails are on outlook365 but when you login on outlook365 it redirects you to our authentication system where you use your student ID and password to login which redirects you back to the mail. Is this possible to configure currently?

Note: initially you use your student email adress to log in, not your student ID. The passwords are the same

I tried this with outlook365 imap and smtp servers and ports I found online, but it doesn't work. In `~/.offlineimaprc` I have this:

[Account finki]
localrepository = finki-local
remoterepository = finki-remote

[Repository finki-remote]
auth_mechanisms = LOGIN
type = Gmail
remoteuser = myfirstname.mylastname@students.finki.ukim.mk
remotepasseval = mailpasswd("finki")
remoteport = 993
folderfilter = lambda foldername: foldername not in ['[Gmail]/All Mail']
sslcacertfile = /etc/ssl/certs/ca-certificates.crt

[Repository finki-local]
type = Maildir
localfolders = ~/.mail/finki

I see that in the error it's redirecting back to gmail's smtp:

$ offlineimap -a finki
OfflineIMAP 7.2.2
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.15, OpenSSL 1.1.1a  20 Nov 2018
Account sync finki:
 *** Processing account finki
 Establishing connection to imap.gmail.com:993 (finki-remote)
 ERROR: Unknown SSL protocol connecting to host 'imap.gmail.com' for repository 'finki-remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
 *** Finished account 'finki' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Unknown SSL protocol connecting to host 'imap.gmail.com' for repository 'finki-remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)

Maybe because I already set my gmail address? I had no problems with it other than the known pinned issue here.

**Comment by LukeSmithxyz** [comment]
This depends on your university's email system. I'll tell you what the University of Arizona does since that's what I know. It's possible that other universities are similar.

Basically you can log into the IMAP server, but it's not with your typical university login/password, but you have to get a secondary IMAP password. [See this link for their example.](https://it.arizona.edu/documentation/catmail-configuration-settings-imap)

The wizard, of course, doesn't and can't be made to do this since it might mean interfacing with every university on the planet's APIs (which they don't even have), so you'll have to do that part yourself and fill out the wizard with what you have.
