### ISSUE TITLE
Using without OfflineIMAP

### ISSUE THREAD

**Issue by bjesus** [LukeSmithxyz/mutt-wizard#126]
Hi! I'm new to Mutt. Thank you for the wizard.

I've tried using mutt-wizard but it seems that it is configured to download all of my emails to my computer. That's almost 20GB, which I'm really not interested in using my disk space for.

I was wondering if there's a way to limit the amount of emails OfflineIMAP saves locally, and still be able to search all emails history when having network connection? If not, is there a way to disable OfflineIMAP completely and just work with the remote server? Are there are special drawbacks to it? For someone who comes from web-mail, this doesn't sounds too bad...

Again, thank you for mutt-wizard.

**Comment by LukeSmithxyz** [comment]
You can check the offlineimap manual for options about filtering the mail you want to download. You won't be able to index it with notmuch unless it's on your machine.

As for not using offlineimap at all, well sure you can do that, but the whole point of the mutt-wizard is configuring offlineimap since it's a pain to mutually prepare it an neomutt and msmtp, etc. Just read the mutt manually and follow its instructions for it looking at a remote IMAP server instead of a local maildir.

**Comment by nirvdrum** [comment]
@LukeSmithxyz For what it's worth, I've used this project because setting up and configuring (neo)mutt is just overwhelming for someone getting started. I was also happy to see your use of gpg to prevent cleartext passwords. I think there's a lot of value in your wizard just for getting (neo)mutt up and running, looking good, good short-cuts, and so on. But, I'm not interested in having to wait for all of my email to sync and searching through headers is generally good enough for me.

So, while I appreciate your stance in not wanting to support the online IMAP case, I think you're underselling the value of your project. Taking the configuration generated by the wizard and then updating it to use an online IMAP server is certainly doable. The gpg stuff needs to manually managed, but also doable. I think it'd be a lot nicer if the wizard could support this use case as well.

Is this a case where you have no interest in supporting it, even if a pull request was submitted?

**Comment by LukeSmithxyz** [comment]
Well I suppose it could be a good idea to add an offlineimap-less option. It would probably actually be a trivial addition.

If you or anyone else wants to add that option feel free to PR it, but I'll go ahead and say that I've been totally rewriting the wizard for a bit (it's on the master branch on Gitlab, but not here) and eventually I'm going to force commit it here, replacing the old wizard.

So what I'm saying is, if it's an easy PR, feel free to do it, but it will only be there as long as this mutt-wizard 1.0 is still around. I'll go ahead and add that as an option to the mw 2.0 though on Gitlab when I get the chance because I suppose you two aren't the only ones who have wanted a feature like that.
