### ISSUE TITLE
POP3 and working on Microsoft Exchange version 8

### ISSUE THREAD

**Issue by marco-silva0000** [LukeSmithxyz/mutt-wizard#134]
my company's email is on an old server with Microsoft Exchange version: 8, and I'm one of the few using linux, and wanted to set this up.

I've made a nmap and I have these(relevant) ports open:
PORT      STATE SERVICE
25/tcp    open  smtp
110/tcp   open  pop3
995/tcp   open  pop3s

as you can see no IMAP, so I was trying to set it up with POP. But I cant figure out witch files to edit.

Do I need to configure it on the account level or the general mutt settings?

**Comment by LukeSmithxyz** [comment]
The wizard doesn't handle pop servers, so this repo isn't necessarily the place to ask.

But if you ran the wizard for this email account, you will want to edit the file in `$HOME/.config/mutt/accounts/NAME.muttrc` and edit it, since it is specific only to your one account.

If you're manually configuring this without using the wizard, you could do either or, but if you have other accounts, you'll want to add ways of switching between them similar to what the wizard does.
