### ISSUE TITLE
.offlineimaprc is not generating correctly

### ISSUE THREAD

**Issue by cgutierrez198** [LukeSmithxyz/mutt-wizard#14]
have to include 
these lines to make it work
[general]
pythonfile = ~/.config/mutt/credentials/imappwd.py
accounts = account1.account2

**Comment by LukeSmithxyz** [comment]
Added this to the readme. You should not have an `~/.offlineimaprc` file when you first run the script. (Delete or remove it). Otherwise, the script will assume that this file is already generated by the script and will not set these settings.

To fix this on your machine, pick the "delete all accounts" option and then add accounts.

**Comment by cgutierrez198** [comment]
alrighty works after deleting the file
thanks
