### ISSUE TITLE
mw cron not working under debain based distros

### ISSUE THREAD

**Issue by Ds886** [LukeSmithxyz/mutt-wizard#145]
in debain based distros the cron service is "cron" and not "crond"*
changing in mw :230 from :
"choosecron() { ! pgrep crond >/dev/null && echo "No cron manager running. Install/enable one and then select this option again." && return 1"
to 
"choosecron() { ! pgrep cron >/dev/null && echo "No cron manager running. Install/enable one and then select this option again." && return 1"
seems to fix it but a check if debian would be more proper

*based on https://www.cyberciti.biz/faq/howto-linux-unix-start-restart-cron/

on a sidenote: as you basically have made a rehaul can you create separate version of the last revision before the rehaul for ease of use for those who used the earlier settings?

**Comment by LukeSmithxyz** [comment]
Okay, I've changed the line to `pgrep -x cron\|crond`. I'm paranoid about running `pgrep` without `-x` in that case.
Do you mean keep up a separate repository or something? Honestly I'm not too interested in maintaining or troubleshooting the old version because this version is just much cleaner. The "settings" in mutt haven't really changed though, and you can still override them, now in your muttrc file.
