### ISSUE TITLE
Invalid path to ca-bundle on Fedora/RHEL

### ISSUE THREAD

**Issue by SteenSchutt** [LukeSmithxyz/mutt-wizard#154]
I ran mutt-wizard on Fedora 29, and mbsync complains about `/etc/ssl/certs/ca-certificates.crt` not existing. This file is named `/etc/ssl/certs/ca-bundle.crt` on my machine. I'm not sure if this extends to all flavors of RHEL, but that's my case anyway. I don't know if this is an upstream problem, or a problem with your wizard, but I worked around the problem by just creating a symlink between the two.

The error appears when trying to configure an email account after putting in my password.

EDIT: This is the problem:
https://github.com/LukeSmithxyz/mutt-wizard/blob/master/bin/mw#L41

**Comment by LukeSmithxyz** [comment]
Yeah I was expecting something like this would happen. I knew the certificates were located somewhere else on Mac OS, but I suppose I have to figure this out for different Linux distros to. I think the current default should work on the Debian, Gentoo and Arch distros, but I need a more robust solution.

If anyone knows a way to detect the ca-certificate location, independent of system, feel free to share it, otherwise I'll draft up a quick fix now.

**Comment by SteenSchutt** [comment]
I believe the classic filename is actually `/etc/pki/tls/certs/ca-bundle.crt`, maybe you can check if that exists on your Arch machine too? Could be there's a path they have in common. The /etc/ssl/certs one is actually a link to that on mine.

**Comment by LukeSmithxyz** [comment]
`/etc/pki/` doesn't exist on Arch.

I've pushed a little detector loop that checks some of the locations that are commonly used:
```{sh}
for x in "/etc/ssl/certs/ca-certificates.crt" "/etc/pki/tls/certs/ca-bundle.crt" "/etc/ssl/ca-bundle.pem" "/etc/pki/tls/cacert.pem" "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
do
	[ -f "$x" ] && sslcert="$x" && break
done || { echo "CA Certificate not found. Please install one or link it to /etc/ssl/certs/ca-certificates.crt" && exit 1 ;}
```
Pull the most recent version and see if it works for you!

**Comment by SteenSchutt** [comment]
Seems to be working fine, thank you!

Appreciate your video on mutt, I was a bit lost behind the learning curve :smile:
