### ISSUE TITLE
[SSL Error] Unable to setup my account

### ISSUE THREAD

**Issue by whereistejas** [LukeSmithxyz/mutt-wizard#158]
```
SSL error connecting imap.gmail.com ([2404:6800:4003:c01::6d]:993): self signed certificate
Log-on not successful.
```
From what I looked online adding `TLSVersions TLSv1.1` to mbsyncrc seems to do the trick.
The mutt-wizard setup just quits in the middle due to this error.

**Comment by tuxfanou** [comment]
Hi @sanaptejas 
My `.mbsyncrc` file is empty.
Did you add only `TLSVersions TLSv1.1` in this file ?
I have this error When I try : `unknown section keyword 'TLSVersions'`

**Comment by sanaptejas** [comment]
> Hi @sanaptejas
> My `.mbsyncrc` file is empty.
> Did you add only `TLSVersions TLSv1.1` in this file ?
> I have this error When I try : `unknown section keyword 'TLSVersions'`

I have the same error.

**Comment by Kr1ss-XD** [comment]
The keyword might be **SSLVersions** instead.

**Comment by sanaptejas** [comment]
> The keyword might be **SSLVersions** instead.
> 
> **Edit** *... of TLSVersions

I tried out your suggestion. It didn't work.
```
/home/user/.mbsyncrc:3: unknown section keyword 'SSLVersions'
Log-on not successful.
It seems that either you inputted the wrong password or sever settings, or there are other requirements for your account out of the control of mutt-wizard.
```

**Comment by Kr1ss-XD** [comment]
Mhmm let's see...  Line 3 of that file seems to be too soon for that keyword. Also, it should actually not be meant to be interpreted as a *section* keyword.

Is that keyword, by any chance, placed in the global (uppermost) settings section of the file, rather than inside the section defining your IMAP connection ?
If so, you should be fine when you move that line below the `IMAPStore` keyword (or below the `IMAPAccount`, in case you have defined that.

If this doesn't solve the issue, it would probably help to understand what's going wrong if you would post your `.mbsyncrc` (after censoring any sensitive data of course).

**Comment by picarda** [comment]
On my side I got this:
IMAP command 'AUTHENTICATE CRAM-MD5' returned an error: NO [AUTHENTICATIONFAILED] Authentication failed. Log-on not successful.
- So the wizzard stoped.

**Comment by picarda** [comment]
Got a Error: SASL(-7): invalid parameter supplied, Log-on not successful. When setup a GMAIL account.
* On OSX

**Comment by nodefive** [comment]
> Got a Error: SASL(-7): invalid parameter supplied, Log-on not successful. When setup a GMAIL account.
> 
> * On OSX

The problem is that when you are setting up a new account (the first one) the script won't write anything to the file mbsyncrc, unless the first setup login succeeds. So I've edited the mw script itself, around line 60, and added there:

```
Host $imap
Port  $iport
User $login
PassCmd \"pass mutt-wizard-$title\"
SSLType $ssltype
AuthMech LOGIN <-- add this here
CertificateFile $sslcert
```

 Once the account was setup I've reverted as it was, in case I need to add another non OAuth acc

**Comment by w3bb** [comment]
Same problem, but after doing the above suggestion I get new errors.
```
Creating profiles for `spiderden`...DONE.
/home/webb/.mbsyncrc:10: unknown keyword 'MaildirStore'
/home/webb/.mbsyncrc:11: unknown keyword 'Subfolders'
/home/webb/.mbsyncrc:13: unknown keyword 'Inbox'
/home/webb/.mbsyncrc:19: unknown store 'spiderden-local'
channel 'spiderden' refers to no slave store
```

**Comment by babdulkarim** [comment]
> Same problem, but after doing the above suggestion I get new errors.
> 
> ```
> Creating profiles for `spiderden`...DONE.
> /home/webb/.mbsyncrc:10: unknown keyword 'MaildirStore'
> /home/webb/.mbsyncrc:11: unknown keyword 'Subfolders'
> /home/webb/.mbsyncrc:13: unknown keyword 'Inbox'
> /home/webb/.mbsyncrc:19: unknown store 'spiderden-local'
> channel 'spiderden' refers to no slave store
> ```

try
```
AuthMech PLAIN
```
instead
