### ISSUE TITLE
long passwords do not seem to work

### ISSUE THREAD

**Issue by oyren** [LukeSmithxyz/mutt-wizard#159]
Hey long passwords still don't work for me, here are some I've tried. 
https://gitlab.com/LukeSmithxyz/mutt-wizard/issues/58

```
user@pc ~ mailsync
C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
IMAP command 'AUTHENTICATE PLAIN <authdata>' returned an error: NO [AUTHENTICATIONF
C: 1/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0
```
further right is a column which shows if the password worked --->

| Password     | Worked |
| ---      | ---       |
| 9e?,^]b'K{6.i;guVP,)H:S&D'X9S@)Q(@"<FjZ^Bo8r$&r6T8Bc]t.J?6!Z2<im2#.8&!Ds'%TQEoh% | no |
| :Fw!'m^gQ]8z"Qe()GhdE^F#u<sz9+7HK?H>R.uJMcM@M%r7kvbYMWK<{$SuyHu'@CW~Kn | no |
| .Y$:<fh]Z6a.aBix)"QKF+'[mfS[2Ex#GaQ=:Na{'Kaw'j@d>T`Ky}VU:"mjo | yes |
| 2FM[(efR3~Hq&:?c:X:3`Z7'7qQ#x!D"JxFs!"ff::m)f*d;Ju"a4BeL9YtS | yes |
| Xj3SKhsXCz57FhYChCyGiskEZM8Dz2ZqyUm6Kqa24pJgw4hxQ57uz3JdfG9ufHFYrGhkn9p4286GPvMXHXZo | no | 
| CWK5cpP5DaNmQmz7UvjJDuctsPX8tvEferrvS34b8khrxP3U3SaEsc98XHQcqDr2WwBdmCvrGDTtY32sbL9r7UQkwxFqDujYTzZ3WPYMFWg29CJyDbzwPtjYhtJxJmZy | no |
| xoN#Pqne(F>Km$>bR};+d^Fz<r9}EjB#bMDs+4sSWrS;ok_vf=vhKD,2J}CJ | no |
| e6`:}g=n]Mnt(qQkux%?/<9Y&x7j.dS`~F(Y2kN(u%zrp#s\jupqJ$@9=S7V-*$+A=@n /v\\]d(XfQ3~WP?)@UGp8)4Vv<,# | no |
| MnhbUQf2eu8_rt5th7sqBvLcycMiq2jKRHrdZihCNXzGEkXQydvwGBSNKAU7FajV | yes |
| KxHp97Nxwhn_dTNxxhKHPVJV6EpFu\qDWzA7s4NHnsNhT2R5unFnsX/F4hK8DtYfhqvW5cZx68ta\6eM8HoZEW_Nr_zdCWYCAfjy33viVmU/6ghewP9mE_93kxizwUpH | no |
| !@p-mvY2C4HHDv;.gqX+#dW5m(sRb/]<&o^aJun<7^>(N}t\e_i?h,EAeu!!d+<3NM\}EvgNdbG:J-3Q]\%d=A,n][9,^2Uv-V:B?\8*`$_m>QGh$r.$-G{=.4qs#uAv | no |

**Comment by LukeSmithxyz** [comment]
What happens if you run `pass mutt-wizard-accountname`? Does it show you long password correctly.

**Comment by oyren** [comment]
Yes it shows my password correctly.

**Comment by d9a** [comment]
I also have this issue. Going from a 128 character password to 30 characters let me log in. I'm glad I checked the issues because I was clueless. I'm wondering if this is a constraint on bash/the environment and not mutt-wizard.

**Comment by Kr1ss-XD** [comment]
I'm more likely to think that there's an issue with either the password handling in `mbsync` or on the IMAP server. There's a couple of reasons for my assumption :
1) Bourne shell has an input limit (i.e., a max. string length) of 128KiB, which is way more than even a ridiculously long password would require,
2) like OP confirmed, `pass` stores and recalls these long passwords correctly, and
3) the setup and everything goes fine until the `mailsync` script calls `mbsync`.

We can take it for granted though that this issue actually relates to the password _length_, since some of the failing password examples (no. 5 & 6) consist of nothing else than alphanumeric characters, thus special characters cannot be the reason.

**Comment by LukeSmithxyz** [comment]
Yeah, this might be a troublesome problem, but it's really not ours. It's likely mbsync's issue and has to do with character encoding and there's nothing we can really do about it. Passwords are given from `pass` right to `isync` and `msmtp` and there's nothing in mutt-wizard that touches much else. So I can't really do anything about this.
