### ISSUE TITLE
url link

### ISSUE THREAD

**Issue by peet1234** [LukeSmithxyz/mutt-wizard#173]
how can i go to url link from neomutt?

**Comment by Kr1ss-XD** [comment]
Just hit `Ctrl+b` and you'll get a list of all URLs found in the current document.

You need to have `urlview` installed though (thx @iMouath for pointing this out btw), and the `lynx` browser to actually open the link.

**Comment by LukeSmithxyz** [comment]
This has been added to the documentation now and provided you have `urlview` installed, but no urlview config, `mw` will will autocreate a config file instructing urlview to use your default `BROWSER` whenever you add a new account.

This makes it easiest for new users.

**Comment by jcguu95** [comment]
I have my urlview installed from AUR (via "yay"). Since it fails to make the most common urlview, I chose urlview-git. Pressing <Ctrl>+b does give me a list of URL in the mail, but it does not spawn URL in my browser (qutebrowser). I checked in my terminal, ($ echo $BROWSER) does give qutebrowser. Did I miss something? Or it is just that urlview does not go well with qutebrowser?

**Comment by Kr1ss-XD** [comment]
U can configure the browser it uses via a configuration file : 
- `/etc/urlview/system.urlview` system-wide config
- `~/.urlview` for a per-user config.

Pls read the manpage `urlview(1)`.

**Comment by jcguu95** [comment]
Thank you! It did work! I also tried the following and it works!
`COMMAND $BROWSER %s`
