### ISSUE TITLE
Migrating accounts from old mutt wizard to new

### ISSUE THREAD

**Issue by BurnyBoi** [LukeSmithxyz/mutt-wizard#191]
I just watched your video on the new mutt wizard and would like to switch to it. I currently have a few email accounts set up using the old wizard, and just wanted to confirm some things before I make the switch:

- If I install the new mutt wizard, will it recognize and work as expected with my existing accounts I've added?

- I've been using offlineimap as configured by the wizard. Is there anything specific I need to do to migrate to using isync instead?

- Will my existing maildir folders be able to migrate?

Any tips you have on moving to the new method as simply as possible would be appreciated. Otherwise, I'll just make sure I have everything backed up and wing it.

**Comment by LukeSmithxyz** [comment]
There is no backwards compatibility because the new version of
mutt-wizard is an independent installable program. The junky config
files that are not muttrcs have been relocated to the share and bin
locations on your computer.

To use the new wizard, backup or simply remove any old config files you
have.

```
rm -rf ~/.config/mutt ~/.config/msmtp ~/.msmtprc ~/.offlineimaprc ~/.config/offlineimap ~/.mbsyncrc
```

Then install the AUR package and run `mw`.

As to "migrating" your downloaded mail from offlineimap to isync, both
download mail as maildirs, so you could just _theoretically_ move your
mail to the new mail location: `~/.local/share/accountname/` without
changes... BUT...

The thing is, and I haven't tried this, is I'm not sure how mbsync will
act if you start your first sync with mail already in the directories.
I'm pretty sure that it will duplicate all of your mail! mbsync keeps
track of mail files with generated files and will treat new files not in
that as something that needs to be synced.

So I think the easiest way to transfer over is to just delete and
redownload everything, which is a pain on the first run, but ensures
that everything will go as intended.
