### ISSUE TITLE
Error message on NeoMutt launch 

### ISSUE THREAD

**Issue by jomonjohnn** [LukeSmithxyz/mutt-wizard#256]
Thank you for the mutt-wizard, it was easy to setup the account. After the setup i observed the following error on console during neomutt launch, is this something need to be taken care ? 

```
Error in /usr/share/mutt-wizard/mutt-wizard.muttrc, line 48: Function 'goto-parent' not available for menu 'browser'
Error in /home/user/.config/mutt/muttrc, line 2: source: file /usr/share/mutt-wizard/mutt-wizard.muttrc could not be sourced.
source: errors in /home/user/.config/mutt/muttrc
Press any key to continue...
```
Distro : Xubuntu 18.04.2 
NeoMutt 20171215

**Comment by Kr1ss-XD** [comment]
This smells as if the `goto-parent` action wasn't implemented in the file browser in your version of NeoMutt.

If my assumption is right, it would help you to install a more recent NeoMutt version from another source, or maybe upgrading your OS (Ubuntu provides NeoMutt 20180716 since 18.10, which definiteley comes with this action).
In case this is not possible, you could change line 48 of `/usr/share/mutt-wizard/mutt-wizard.muttrc` as follows : 
```
macro browser h '<change-dir><kill-line>..<enter>' "Go to parent folder"
```
To answer your question, by the way: yes, this should be taken care of, since the error message suggests that the basic configuration file can't be loaded at all because of the according line.

**Comment by LukeSmithxyz** [comment]
Yes, as Kr1ss says, `goto-parent` has not been included in recent Ubuntu versions. As the readme says:

>>> There's a chance of errors if you use a slow-release distro like Ubuntu, Debian or Mint. If you get errors in neomutt, install the most recent version manually or manually remove the offending lines in the config in /usr/share/mutt-wizard/mutt-wizard.muttrc.

This is really in response specifically to `goto-parent`.

Of course, if Kr1ss's proposed solution works the same way and works for all systems, I might just include it as default to avoid the problem.

**Comment by jomonjohnn** [comment]
Thanks to @Kr1ss-XD and @LukeSmithxyz . As suggested i manually pulled the latest debs with associated dependencies (libncursesw6_6.1 and libtinfo6_6.1) from packages.ubuntu.com and installed NeoMutt 20180716. Now there is no error messages on startup.
