### ISSUE TITLE
Checking for wrong input when purging

### ISSUE THREAD

**Issue by mariuskiessling** [LukeSmithxyz/mutt-wizard#261]
When using the `mw purge` command, the user is prompted to either enter `y` or `N`.
```
Do you want to delete all account data? [y/N]
```

However when entering `y`, the input is not accepted and the following message is printed:
```
That doesn't seem like a yes to me.
```

In order to prevent confusion, I suggest changing the question to:
```
Do you want to delete all account data? [yes/N]
```
https://github.com/LukeSmithxyz/mutt-wizard/blob/c37a748227a7c81519ae73cdbb69f3a3368833f8/bin/mw#L246

If you think this is okay, I will happily open a pull request.

**Comment by LukeSmithxyz** [comment]
I can't replicate this issue. `grep -i "^y$\|^yes$"` checks for both `y` and `yes`.

**Comment by mariuskiessling** [comment]
@LukeSmithxyz Thanks for the quick response. I executed the grep command separately, however my version of grep does not seem to work with this regex.
```
$ echo "y" | grep -i "^y$\|^yes$"
$ echo "yes" | grep -i "^y$\|^yes$"
yes
$ grep --version
grep (BSD grep) 2.5.1-FreeBS
```

If you think this is an edge case, just go ahead and close the issue. Otherwise, I suggest switching to an awk command to parse and execute the regex. What are your thoughts on this?

**Comment by nodefive** [comment]
This is happening because you are either using a Mac or some flavor of BSD!

`  worker [~] $ echo "y" | grep -i "^y$\|^yes$"

  worker [~] $ echo "y" | ggrep -i "^y$\|^yes$"
y

  worker [~] $ grep --v
grep (BSD grep) 2.5.1-FreeBSD

  worker [~] $ ggrep --v
ggrep (GNU grep) 3.3
Packaged by Homebrew
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.`

The error happens because of a bug on the BSD grep:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=201650

If you are on a Mac you can install a GNU grep via "brew install grep" (install as ggrep).
If you are BSD you can get the src for grep and rebuild it.
