### ISSUE TITLE
notify-send not showing messages

### ISSUE THREAD

**Issue by deadpyxel** [LukeSmithxyz/mutt-wizard#282]
## Expected Behavior

`notify-send` should show a message when new email has been synced

## Current Behavior

There's no notification shown in either manual and cron synchronization.

## Possible Solution

Maybe I set up `notify-send`incorrectly?

## Steps to Reproduce (for bugs)

1. Install mutt-wizard using yay
2. Check the listed dependencies are installed
3. setup email and sync for the first time
4. do a manual sync or set a cron sync using the `mailsync` command
5. No notification on new mail (even when I send email to myself)

Important: I still receiving email normally, so must be something wrong with `notify-send`

## Context

In my Ubuntu machine this feature is working fine (except for the cronjob, that I'm looking at), right now all else in my Archlinux install works fine, except the notification message on synchronization.

## Your Environment

* Version used: Latest AUR version as of today
* Kernel version: 5.2.11-arch1-1-ARCH
* notify-send version: 0.7.8
* Operating System and version: Archlinux x64
* I'm using `zsh` and `oh-my-zsh`

**Comment by Kr1ss-XD** [comment]
Hi, thx for the report.

Since new email notifications do work on my end, I think we can sort this out. Could you please try
```
notify-send <some_random_text>
```
in a shell and see if you get a notification popup ?

- If no, does the command output an error message, and what is it about ?
What environment are you running in terms of desktop / window manager ?

- If yes, have you installed the official `libnotify` package from Arch's `[extra]` repo, or some alternative package from the AUR ?

**Comment by deadpyxel** [comment]
@Kr1ss-XD thanks for the quick reply. I tried the command and nothing showed up, neither errors.

About `libnotify`, I believe it is the official `pacman`, but can I confirm that by any means? Maybe something overwrote it and that's conflicting.

**Comment by Kr1ss-XD** [comment]
You can.

`pacman -Q libnotify` should yield `libnotify 0.7.8-1`.

Also, you can check if all the files which were provided by that package are genuine with

```
pacman -Qkk libnotify
```

There's one dependency, `gdk-pixbuf2`, which you could also check. If both packages are correctly installed, we likely need to dig into that one's deps, which are quite a bunch.

**Comment by deadpyxel** [comment]
@Kr1ss-XD Just did the checks.

Both seem to be authentic and not modified. I was thinking, is there any debug mode for `libnotify`?

**Comment by Kr1ss-XD** [comment]
On a first glance, there isn't. That's why I was asking for your desktop/window manager environent. Maybe there is an issue with the d-bus protocol on your system.
I'll try to dive into the documentation that comes with `libnotify` tomorrow and get back to you.

On the other hand, I could investigate if there's some kind of notification system which could be used as an alternative.

**Comment by deadpyxel** [comment]
Oh, I didn't pay attention to the WM part.

I'm using i3-gaps from pacman repository, `version 4.17.1 (2019-08-30)`.

If you think there's something wrong with D-BUS, I can try yo debug it. What would I need to do?

Sorry for the late reply, I was having classes.

**Comment by Kr1ss-XD** [comment]
Okay. Since you're on i3, my best guess is that you probably don't have a notification daemon. There are quite a few alternatives.

From the top of my head, at least `dunst` and `notify-osd` are in the Arch repos. Either one should work fine, though I think dunst is more flexible and more configurable.
Try installing one of them. If I'm right with my assumption, you're good to go then.

**Comment by deadpyxel** [comment]
@Kr1ss-XD cool, just tried it, and now I have notifications, they just seem be acting a little bit weird.

**Comment by deadpyxel** [comment]
@Kr1ss-XD An update: After a restart the notifications work and look fine. Thanks for your help. I believe this information would be useful to be added as a FAQ or general info in the README.md

**Comment by Kr1ss-XD** [comment]
That's great, you're welcome !  :rocket: :+1: 

I agree it would be nice to have some hint in the documentation, though it's actually more subject to the notification system and/or the DE/WM and not mutt-wizard specific.

Concerning the look of the notifications, I believe dunst can be confiigured in a way that the notifications show up above the i3bar, between the workspace symbols and i3status messages. This would kind of look like native to i3.

**Comment by deadpyxel** [comment]
@Kr1ss-XD That's cool. All is working now, I just have to figure `pam-gnupg` now. Thanks for your help. You can mark this issue as closed.

**Comment by Kr1ss-XD** [comment]
You can do so, since you were the opener :wink:
