### ISSUE TITLE
not working on Qubes and Split-GPG system

### ISSUE THREAD

**Issue by nosyaardvark** [LukeSmithxyz/mutt-wizard#320]
Hello, and thanks for your efforts.

I'd like to use the `wizard` on Qubes, but using the [Split-GPG](https://www.qubes-os.org/doc/split-gpg/) system - that is, mutt email handled in one virtual machine ('qube') that is connected to the big bad world of the internet, but gpg keys handled in a separate gpg-only qube that is isolated from the internet. The 'tunnel' btween the two qubes is handled by the `qubes-gpg-split` application. 

Have run the command `mw` and now I am pretty much stuck at the very start - `pam` needs the keys that are on the other qube, and I don't know how to handle it.

Am I simply asking too much? (My level of knowledge is admittedly quite low and I am a new Qubes user).

(Also, `pam-gnupg` isn't available to Fedora 29, it seems).

PS/Edit - made [a post on reddit](https://www.reddit.com/r/Qubes/comments/drhpw2/mutt_wizard_in_qubes/), too.

**Comment by vitaliy-kuzmich** [comment]
@LukeSmithxyz Hi, thank you a lot for this tool, and information on youtube. I want to request video about configuring GPG with https://github.com/cruegge/pam-gnupg, because I did everything as said, but it still asking for the gpg password after login. I have same password for system, and gpg.  Check this : https://github.com/cruegge/pam-gnupg/issues/6, I am not alone, or maybe just include pam as an option in mw ?

**Comment by kristog** [comment]
I have the same problem here, I followe the qubes documentation about split gpg and mutt and added all the specified settings in my muttrc, I can sign mails, encrypt mails, I can open signed mails but it fails to open encrypted mails. The problem seems to be the way neomutt handles these lines :

set pgp_decode_command="qubes-gpg-client-wrapper --status-fd=2 --batch %f"
set pgp_decrypt_command="$pgp_decode_command" 

Interestingly, if I try with mutt (not neomutt) everything works.
