### ISSUE TITLE
isync and privacy issues

### ISSUE THREAD

**Issue by whew** [LukeSmithxyz/mutt-wizard#334]
You use isync, which stores mail in a plain text. I find this very insecure, considering how carefully a password is protected in your bundle. Anyone who has access to SSH can actually download the entire, ready-made mail archive and read it all. There is no need to crack passwords, and the folder address is already specified in the mbsync configuration.

I'm thinking about how to improve it and I can't come up with a universal answer. There are two options:
1) Download mail, run `mutt`, `mw` and `mbsync` from a separate user. In conjunction with the sudo ssh prohibition, this is actually an impenetrable tactic. Allows you to read offline mail and connect via, for example, `sudo -u mutt neomutt`
2) Encrypt the mbsync folder. How - I don't know. And to do so, you will have to reconfigure mutt to access the encrypted folder.

I also have a meta question. Why do we need isync at all when mutt can store mail in its cache and encrypt it?

**Comment by LukeSmithxyz** [comment]
Stored mail is as secure as any other personal file in your home directory and users without your permissions cannot access them. I don't think that's too unreasonable.

For me, I'll say the whole point of having nice unencrypted files is that they can easily be searched and controlled via command line tools and other personal scripts, something which I do pretty often. Maybe I'm blasé for thinking that all the security you need is in user-login, but browsers nowadays all store _all_ your saved passwords in places that even normies know how to read immediately if you just let them use your computer for a moment.

Now passwords are encrypted now because:
- People reuse the same password for multiple things.
- It's easy accidentally compromise your password by sharing dotfiles or someone using your machine or watching you. I.e. in early videos, I got close to accidentally showing unecrypted passwords when I moved over `~/.offlineimaprc` in ranger or something. Stuff like that.
- msmtp will literally just not allow you to send mail with a password in a file (you can change the permissions to only be readable by you, but that's just as secure as mail is in mutt-wizard anyway).

Of course I don't mind having increase security, just in case. But I wouldn't want to lose any of the above functionality.

I think your idea to have a separate mutt-wizard user is an interesting one, and people like me could easily add their users to groups that can freely read all their own mail if desired.

> I also have a meta question. Why do we need isync at all when mutt can store mail in its cache and encrypt it?

mutt doesn't encrypt cached bodies... Well, maybe there's an optional setting I've missed to encrypt stored mail, but mutt will cache bodies more or less the same way isync does. If I'm wrong I'd like to see the option.

More prominently, mutt caches emails that you manually open in mutt, isync, however, can be run at any time even if mutt is closed and even if you haven't opened the mail yet. Again, maybe there's some secret option to cache all mails automatically (and a command that can check mail without always having a mutt window open), but I don't see it in the documentation.
