### ISSUE TITLE
Filtering out labels from INBOX

### ISSUE THREAD

**Issue by jevy** [LukeSmithxyz/mutt-wizard#346]
Hey Luke,

It's been 15 years since I've used Mutt last so I'm excited to try it again.

I've added labels to all the incoming email into "Promotions" (label: MyPromotions) and "Social" (label:MySocial). I would like to keep these out of my INBOX folder and after an hour playing with it, I can't figure out how. Any ideas?

Jevin

**Comment by jevy** [comment]
I think I found a solution and I'm just working through it:
mbsync -> notmuch -> [Label sync between notmuch and gmail](https://github.com/gauteh/lieer) -> notmuchfs for filtering out labels from inbox -> mutt reading that new virtual maildir

**Comment by LukeSmithxyz** [comment]
Yeah this is something case specific for Gmail and some other tag-based email services. It's pretty hard to automate this in mutt-wizard since you would be enforcing a specific configuration on everyone.

When I have to use a Gmail account, for example, I don't allow it to label mail so that simplifies it, but you'd have to figure it out how you'd like it if you do use them.
