### ISSUE TITLE
`alternative_order` has to be set before loading `/usr/share/mutt-wizzard/muttrc`

### ISSUE THREAD

**Issue by CosmosAtlas** [LukeSmithxyz/mutt-wizard#371]
I'm trying to set `alternative_order` to load `text/calendar` before `text/html`. However, the only way I figured it would work is when I put `alternative_order` before loading the default muttrc file.

Putting this information here in case anyone else is facing the same problem.

**Comment by rjl6789** [comment]
Note: came across this 'issue' myself when trying to separately specify an order for a particular account.  The `alternative_order` seems to be an additive list.  In order to change it you can clear it with `unalternative_list *`, then reset it with a call to `alternative_list`.  The disadvantage of this is that this will be the new "default" when switching to other accounts, unless you play the same trick in their configs.
