### ISSUE TITLE
Anyone have any success on OpenBSD?

### ISSUE THREAD

**Issue by hamlinux** [LukeSmithxyz/mutt-wizard#372]
"doas make clean install" results in.

*** Parse error in /home/$USER/git/mutt-wizard: Need an operator in 'PREFIX' (Makefile:4)
*** Parse error: Need an operator in 'endif' (Makefile:6)

**Comment by epsilon-0** [comment]
@hamlinux 
Couple of comments.
Don't do doas... mutt-wizard doesn't need full access for local installation. Unless you want to install this package for everyone on the system (which in most cases for single person computers is just the user and root) I would do this only locally.
To do the install you should try to pass the PREFIX manually such as
```
PREFIX=/home/$USER/.local make clean install
```
I don't know if this will work though, because of GnuMake vs BSDMake, given their different notations and the use of $DESTDIR and $PREFIX.

But this is a good starting point.

**Comment by eleblanc** [comment]
If you install gmake, you should be able to install mw.

**Comment by hamlinux** [comment]
Will give a try.  I have gone to vanilla Mutt on my Linux and OpenBSD
machines with separate muttrc files for different email accounts.

**Comment by eleblanc** [comment]
Also, once mw is installed, you will need to install ggrep (pkg_add) and change all invocation of grep to ggrep in /usr/local/bin/mw (you don't need to change the pgrep invocation). With that, everything should work!

**Comment by epsilon-0** [comment]
Somebody should make a port for this :)

**Comment by motorto** [comment]
@epsilon-0 a lot of linux distros, (I don't know if port follow this as well) don't allow the use of the git repo directly (git clone) to create packages.

One way to fix this would by creating releases with the usage of tags, this was previously asked #402

**Comment by epsilon-0** [comment]
@motorto  I've packed this for Gentoo - https://packages.gentoo.org/packages/mail-client/mutt-wizard
and also a WIP port for OpenBSD which hopefully should get in as well - https://marc.info/?t=159098685900001&r=1&w=2

So theres atleast some methods of getting this to work.

**Comment by motorto** [comment]
I am assuming that Gentoo allows git packages , the distro that I am
using doesn't (Void Linux). I am pretty sure that another distros have
the same behaviour (the git repo usually is not "stable" , that's
why the release tags exist).

**Comment by Kr1ss-XD** [comment]
Not sure if this is conformant on Void @motorto - but since no tags are available you could maybe pin the package to a certain commit ? E.g. pull from
```
 https://github.com/LukeSmithxyz/mutt-wizard#commit=95cf003c036dd95000ab80ca6c680dab2e3ca092
```
:question:

**Comment by motorto** [comment]
Pretty sure they don't allow that , it's not up to me to decide in which
commit the program is stable ...

Unless Luke Smith (I think he is the only one with ability to modify the
project) , creates a release tag , a lot of Linux distros won't receive
this as a package.

Me personally I no longer use this program since I learned and
mature on neomutt , but I know the importance and how easy this app 
makes to configure emails accounts with mutt/neomutt and someone how is
beginning or simply doesn't have time to configure by hand every single
one of his email accounts can enjoy and use.

**Comment by Kr1ss-XD** [comment]
>Me personally I no longer use this program since I learned and
>mature on neomutt , but I know the importance and how easy this app
>makes to configure emails accounts with mutt/neomutt and someone how is
>beginning or simply doesn't have time to configure by hand every single
>one of his email accounts can enjoy and use.

:+1:
Same here, fiddling with the wizard was extremely helpful to learn configuring 
(neo-)mutt.

**Comment by hisacro** [comment]
It's in [ports now](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/mail/mutt-wizard/)

I don't use it (mutt & alpine all the way) 
found from recent commit     
maybe it'll help future testers.

**Comment by epsilon-0** [comment]
> Somebody should make a port for this :)

lmao, when I look back at my old comments :smile_cat: 

I'm going to try and keep doing monthly updates for my port, unless those are only domains updates, in which case I will skip.

**Comment by cizordj** [comment]
I have a similar problem on FreeBSD, the way to solve this is by installing the Gnu's version of Make

**Comment by epsilon-0** [comment]
This issue can be closed now.
mutt-wizard is available in ports in OpenBSD
