### ISSUE TITLE
Not working with Protonmail bridge

### ISSUE THREAD

**Issue by RononDex** [LukeSmithxyz/mutt-wizard#374]
I used `mw add` to add my proton mail account (protonmail-bridge is installed and running) and keep getting this error message when opening neomutt:
`gnutls_handshake: An unexpected TLS packet was recieved`
![image](https://user-images.githubusercontent.com/2249071/75149470-5cff2e80-5702-11ea-8a51-a8da412f41f1.png)

**Comment by thepenguinthatwants** [comment]
Have u tried  emersion/hydroxide ? That might work.

**Comment by ajoubert** [comment]
This might be because your bridge doesn't support TLS?
You could try having a look at `~/.config/mutt/accounts/<your-mailbox>.muttrc` and change the `folder=` variable to use `imap=` instead of `imaps=`?

If this works, I don't know if the solution would be to keep this more 'insecure' communication (since the bridge runs on your local machine I guess it should be fine?) or if something in the protonmail bridge needs to be fixed/configured.
