### ISSUE TITLE
e-mail sent twice unless "set copy = no" included in muttrc

### ISSUE THREAD

**Issue by catalyst1987** [LukeSmithxyz/mutt-wizard#384]
Hello,
    I noticed that when I setup my outlook account via mutt-wizard that the muttrc file for it does not have "set copy = no" included in it by default.  As a result you end up sending a mail to the sender twice.  Would suggest changing this in the wizard if possible  

Thanks for mutt-wizard.  Its a great tool.

**Comment by BachoSeven** [comment]
I can confirm this behaviour with gmail as well, thanks for the tip!

**Comment by travs** [comment]
@catalyst1987 @BachoSeven 

Can you confirm if it's actually sent twice, and not just put in your sent mail twice?
When I test this with a gmail account the recipient only gets one copy, but I have two copies in my sent mail.

I assume this is just because gmail/outlook is independently doing same thing mutt is doing (storing a copy of sent mail in outbox).

**Comment by BachoSeven** [comment]
I confirm that indeed the recipients only receive one copy; thus it is
just duplicating the copy in my sent mails. I fixed it as mentioned now,
though.
