### ISSUE TITLE
Google Mailboxes

### ISSUE THREAD

**Issue by ralpheeee88** [LukeSmithxyz/mutt-wizard#40]
Is there a way to re-scan mailboxes? Am just wondering because some folders from my gmail account are not showing (sent mail, all mail, drafts) I have a mail box labelled [Google] but when i try to open it i get the error msg thats its not a mailbox

**Comment by LukeSmithxyz** [comment]
If you just downloaded the script in the last day or so, I had accidently pushed some errors onto the master branch that messed up mailbox detection. You might want to pull the updated master, remove the account you added and readd it.

I will say that "All mail" is by default deactivated by the scripts (you can change this in `~/.offlineimaprc`). This is just because of the way Google stores mail, having "All mail" would just double download all your mail files.

**Comment by ralpheeee88** [comment]
@LukeSmithxyz ok thxs ...will pull....(need to back up my colors and various tweaks i did)
