### ISSUE TITLE
<ctr> b not detecting url links in all emails

### ISSUE THREAD

**Issue by pauljamesharper** [LukeSmithxyz/mutt-wizard#406]
I am using Debian 10 Buster. Some html emails work with ctr b to find a numbered list of urls. Other emails like the newsletter <noreply@getpocket.com> do not work to render the html. I can see the text but not get the urls.

Below the subject line there is:
`│[-- Autoview using w3m -I 'utf-8' -T text/html --]
`
Is there something that needs to be added to the mailcap file to get all the URLs to render?

Thanks for a really useful program. I have Gmail, Protonmail and my works Office365  working correctly otherwise.

**Comment by LukeSmithxyz** [comment]
Finding urls is actually done with the external program `urlview`. What regular expressions it looks for is defined inside its config file and you can change. Look up urlview and you'll get your answers.

I myself don't actually use this functionality of mutt-wizard because I have a binding in my terminal that selects and follows found urls.

**Comment by pauljamesharper** [comment]
Thanks for that information. I will do some research. Now I know where to look.
