### ISSUE TITLE
Pass

### ISSUE THREAD

**Issue by lol2718** [LukeSmithxyz/mutt-wizard#420]
How can I make sure that pass keeps my mail password after reboot. I have a cronjob set up. It is really annoying to need to retype the password every time I boot into my system.

**Comment by AlexBocken** [comment]
Do you mean you have to retype your master password for pass everytime you reboot? I reccomend you keep it like that since your password will be completely unencrypted otherwise.

If you don't care about security, you can always edit your `~/.mbsyncrc` to not even use pass. Just use for the `PassCmd`:

```bash
PassCmd "echo <your password here>"
```

I want to emphasize that this solution is extremely unsafe and imo should not be used. But it's your PC and your email account. Personally I just have pass on an extremely long timeout time so I only have to enter my password once for each session.

**Comment by aleksozolins** [comment]
You need to use pam-gnupg to pass your login password to gpg. The MW manual talks about this.
https://github.com/cruegge/pam-gnupg
