### ISSUE TITLE
Inconsistency when starting neomutt

### ISSUE THREAD

**Issue by axelcalixte** [LukeSmithxyz/mutt-wizard#445]
Hello, the issue might not be related to mutt-wizard but I'll ask anyway hoping it's a small fix.

When I start neomutt with my keybind on dwm SHCMD("st -e neomutt"), I can't send mail. I get this error after pressing 'y'. 
![Images](https://user-images.githubusercontent.com/55485674/83104626-6b6e3500-a0b9-11ea-81a6-9fc8a8a3dbff.jpg)

Thanks in advance,
Axel

**Comment by qorg11** [comment]
Try changing` passwordeval` to `password "your smtp password" `in `~/.config/msmtp/config`. That way msmtp don't have to eval the pass command to get the password. It just get the password

**Comment by f380cedric** [comment]
> When I start neomutt with my keybind on dwm SHCMD("st -e neomutt"), I can't send mail. I get this error after pressing 'y'.

That is because your keyring is not unlocked. msmtp runs pass to get your SMTP credential, and pass runs gpg to decrypt the file containing the credential. If the key is in gpg-agent, gpg can decrypt without user input. If it is not, then it needs user input to get the passphrase to read your gpg private key. It uses pinentry to request the passphrase.

I suspect your pinentry is terminal based (eg curse). To draw in the st terminal, pinentry needs to know to witch virtual tty st is attached. 
This is done by setting the GPG_TTY environment variable. You may have `export GPG_TTY=$(tty)` in your *.bashrc*, but it is only read by non-login interactive shell.

So, possible solutions:
 - Have your gpg keyring unlocked before msmtp invocation (eg via `pam_gpg` or unlock manually and/or play with gpg-agent cache expiration).
 - Install a GUI based pinentry (eg gtk, qt, grc).
 - Use `st -e sh -c 'GPG_TTY=$(tty) neomutt'` (`'` and not `"`, or you will need to escape `$`).
 - Use `st -e bash -ic 'neomutt'` if you need multiples environment that are *dynamically* set in your *.bashrc*.

NB: do not use pinentry-tty with mutt, it breaks things. Use pinentry-curse (Arch Linux uses pinentry-curse or GUI based ones, so if you use Arch, you are safe).

**Comment by axelcalixte** [comment]
Thanks guys for the help !

I had a gtk2 pinentry and everything worked when simply starting neomutt in a shell.
I didn't want to try qorg11 method because it would mean having my password in a simple text file.
I solved the issue by changing the shortcut to "st -e zsh -ic 'neomutt'" in my dwm build.
