### ISSUE TITLE
Mailsync doesn't show notification at all

### ISSUE THREAD

**Issue by Ingvix** [LukeSmithxyz/mutt-wizard#470]
Notify-send is working well independently but mailsync gives no notifications, not when running by myself nor as a cronjob. Any help would be appreciated. I'm using the latest version of mutt-wizard.

I'm on Void Linux.

**Comment by f380cedric** [comment]
Can you check that `echo $DBUS_SESSION_BUS_ADDRESS`and `echo "unix:path=/run/user/$(id -u)/bus"` (in a shell where notify-send works) return the same string? I do not know Void Linux, but it may configure dbus differently than OS with systemd as init.

**Comment by Ingvix** [comment]
They return quite different strings in fact. $DBUS_SESSION_BUS_ADDRESS in a terminal is "unix:abstract=/tmp/dbus-oiibAoK57i,guid=e5f89a6777e2e184b810e2b55eeb73b4".

**Comment by f380cedric** [comment]
So that is the issue. notify-send communicates with DBUS, so it needs to know the address.
With that address path, I guess it will change every time you log off/on (or reboot). But I am not a DBUS expert...

**I encourage you to reach other Void Linux user** (eg Void Linux forum or IRC) because it seems to be Void Linux DBUS specific.

Anyway, I will provide some (possible) workarounds.

Have you [configured DBUS](https://docs.voidlinux.org/config/session-management.html?highlight=dbus#d-bus)? It would be nice if, after configuration, you get a static bus address.

From [some DBUS doc](https://dbus.freedesktop.org/doc/dbus-launch.1.html), it is stated:

> If DBUS_SESSION_BUS_ADDRESS is not set for a process that tries to use D-Bus, by default the process will attempt to invoke dbus-launch with the --autolaunch option to start up a new session bus or find the existing bus address on the X display or in a file in ~/.dbus/session-bus/

I expect that if you comment out [line 15](https://github.com/LukeSmithxyz/mutt-wizard/blob/e2203ed34f5f74b1d7b4651f35feaa86426bd087/bin/mailsync#L15) (the one that setup the DBUS environment variable), it may work. But not sure knowing it runs in cron.

Or maybe DBUS write something useful under `~/.dbus/session-bus/` (it is discussed a bit [here](https://old.reddit.com/r/voidlinux/comments/b7csfl/notifysend_from_cron/), but not very conclusive, maybe you can source it?).

Or use something like [this](https://unix.stackexchange.com/a/111190).

**Comment by Ingvix** [comment]
I ended up with following solution:

At session start I run `dbus-launch --exit-with-session dwm` which creates a file ~/.dbus/session-bus/<machine-id>-<display> which contains the needed address among other variables. The recommended way to start a WM/DE-session with DBus according to Void Wiki is to use `dbus-run-session` but not every WM(like bspwm and dwm, but apparently with i3 it works) take in the DBus variables it provides for the session, therefore starting `dbus-launch` automatically when some process attemps to use dbus so I cut the middle-man by starting the session with `dbus-launch`.

In `mailsync`, I commented out the current export commands for display and DBus address and changed notify() and messageinfo() functions to following:
```
    notify() {
	for session in $HOME/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-*; do
	    . $session
	    export DBUS_SESSION_BUS_ADDRESS
	    export DISPLAY=:${session##*-}
	    notify-send --app-name="mutt-wizard" "mutt-wizard" "📬 $2 new mail(s) in \`$1\` account." 
	done
    }
    messageinfo() {
	for session in $HOME/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-*; do
	    . $session
	    export DBUS_SESSION_BUS_ADDRESS
	    export DISPLAY=:${session##*-}
	    notify-send --app-name="mutt-wizard" "📧$from:" "$subject"
	done
```
So they loop through all the session files in ~/.dbus/session-store so I get the notifications to every graphical session I might be in.

Finally at the end of .xinitrc I have the following:
`rm -f ~/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-${$DISPLAY##:}`
since `dbus-launch` doesn't seem to remove the session files itself. It probably likes to use the same file if possible but I don't want mailsync sending notification to unexistent sessions so I remove them. While writing this I also realized I should also probably empty the directory at boot and shutdown to cover all the bases.
