### ISSUE TITLE
Problem for sending emails

### ISSUE THREAD

**Issue by farbod777** [LukeSmithxyz/mutt-wizard#474]
I have tried to configure my email server but I can only receive and not send.
I have tried to set the email with Thunderbird multiple times inserting the correct parameter but nothing.
Still thunderbird send the email but will never arrive, I have tried DKIM test but will never start.
I post here the output of journalctl -xe when i try to send the email.

pls help me 

> Jun 24 17:57:06 Simurgh postfix/smtp[22893]: connect to gmail-smtp-in.l.google.com[2607:f8b0:400d:c01::1b]:25: Connection timed out
Jun 24 17:57:36 Simurgh postfix/smtp[22893]: connect to gmail-smtp-in.l.google.com[172.217.197.27]:25: Connection timed out
Jun 24 17:58:06 Simurgh postfix/smtp[22893]: connect to alt1.gmail-smtp-in.l.google.com[2800:3f0:4003:c00::1a]:25: Connection timed out
Jun 24 17:58:36 Simurgh postfix/smtp[22893]: connect to alt1.gmail-smtp-in.l.google.com[64.233.186.26]:25: Connection timed out
Jun 24 17:59:06 Simurgh postfix/smtp[22893]: connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:400b:c03::1a]:25: Connection timed out
Jun 24 17:59:06 Simurgh postfix/smtp[22893]: 0AA4220F79: to=<farbodrassouli@gmail.com>, relay=none, delay=151, delays=0.45/0/150/0, dsn=4.4.1, status=
Jun 24 17:59:56 Simurgh postfix/anvil[22897]: statistics: max connection rate 1/60s for (submission:151.72.35.188) at Jun 24 17:56:35
Jun 24 17:59:56 Simurgh postfix/anvil[22897]: statistics: max connection count 1 for (submission:151.72.35.188) at Jun 24 17:56:35
Jun 24 17:59:56 Simurgh postfix/anvil[22897]: statistics: max cache size 1 at Jun 24 17:56:35
Jun 24 18:00:07 Simurgh sshd[22918]: Connection closed by 45.91.24.77 port 41010 [preauth]

**Comment by SentToDevNull** [comment]
This project is for configuring an email client, not a server. (You might have selected the wrong project's issue tab submitting this.)

Anyways:

Google (and most other mail hosts) soft reject your mail like that if your SPF, DKIM, and DMARC records weren't all set up properly, if your DKIM service wasn't configured correctly, if your cert is invalid, or if you are using a less secure protocol. You should also check to see if your IPv4/IPv6 addresses or domains are on any public blocklists and petition to get them removed if they are.

Any error at all in the setup of those components of your server will get you placed on a public blocklist if you try to connect to a host like Google too many times.

Sidenote: I've had my emails rejected like this before. Tutorials you'll find for setting up your own mail server tend to have a very short shelf life due to the number of components needed to get things working, so reading the official documentation (e.g. `man postfix` or `man opendkim`) is always the best way to go.
