### ISSUE TITLE
configure mutt-wizard with a tls mail server

### ISSUE THREAD

**Issue by paindespik** [LukeSmithxyz/mutt-wizard#477]
Hi! 
I am trying to configure mutt using mutt wizard, and i created a mail server folowing this video https://youtu.be/9zP7qooM4pY.
But it seems that the mail server uses TLS and not SSL, and i can't manage to add this mail to mutt. When I run 'mw add', i get this error:
_Socket error: secure connect to mail.seandriard.xyz ([2001:19f0:6801:16ee:5400:2ff:fed8:e097]:143): error:1408F10B:SSL routines:ssl3_get_record:wrong version number_
So mutt wizard must be configured only for ssl mail server.
Is there a way to make mutt wizard accept TLS?
Thanks a lot

**Comment by f380cedric** [comment]
IMO, It is because you are setting up IMAP on port 143, meaning it uses plain text, with the possibility (depending on your server configuration) to upgrade that plain text connection to an encrypted one.

But it seems that mutt-wizard does not handle IMAP STARTTLS during the configuration procedure.
The issue was raised in #66 but was later closed by the author.

My suggestion is to use the port 993 (IMAPS, IMAP over TLS). It seems that IMAP over STARTTLS is not often used.
Or if you definitely need IMAP over STARTTLS, change `SSLType IMAPS` to `SSLType STARTTLS` in `$HOME/.mbsyncrc` and (maybe) try to reopen #66.

NB: SSL and TLS are related. The protocol was called SSL up to SSL 3, but then was renamed to TLS (and the version number was reset, starting with TLS 1). Support of SSL/TLS versions mostly depends on your cryptography library (your seems openssl like). If your system is up to date (and not EOL!), it should support at least TLS 1.2.

**Comment by paindespik** [comment]
Worked perfectly with port 993, thanks
I did not know TLS was a version of SSL, and my error message now makes more sence.

**Comment by f380cedric** [comment]
@paindespik is your issue solved? If yes, could you close it? Thanks
