### ISSUE TITLE
Query About signature.asc as attachment

### ISSUE THREAD

**Issue by utkarsh181** [LukeSmithxyz/mutt-wizard#482]
I have used mutt-wizard to configure mutt, everything is working great but I have a query regarding an attachment sent with my email. As per my knowledge these are my public pgp keys but **are they required**  I don't have much knowledge to cryptography. I have also attached screenshot of the attachment and i am using gmail as my mail provider.
![pic-full-200701-2328-02](https://user-images.githubusercontent.com/56307408/86277379-37c08680-bbf4-11ea-8036-19e7b7f8f061.png)

**Comment by f380cedric** [comment]
It is due to the default settings of mutt-wizard, in your `~/.config/mutt/accounts/?-accountname.muttrc`

```
set crypt_autosign = yes
set crypt_opportunistic_encrypt = yes
set pgp_self_encrypt = yes
set pgp_default_key  = $keyid
```
where `$keyid` is the ID of you gpg key associated to your address mail (if mw found one). 
So, by default:
 - encrypt mails you send if it found public keys of all recipients (1)

and if mw found your `$keyid`:
 - sign your message with your private key, so that recipient can verify the mail is written by you with the knowledge of your public key (2)
 - in the case of (1), also encrypt for you, allowing you to read the encrypted mail in you record folder (Sent)

The signature (2) is attached to your mail, it is the signature.asc file.
If you do not want to sign your message, you can switch `crypt_autosign` to `no`. If you do not want to use pgp at all, you can comment these lines.
