### ISSUE TITLE
Can't email from 2 of my three email accounts

### ISSUE THREAD

**Issue by t0ta1packag3** [LukeSmithxyz/mutt-wizard#493]
I set up three email accounts (protonmail, enterprise through webmail, and gmail). The protonmail works perfectly, but when I try to send mail through either the webmail or the gmail, I get this error:

`secret key '[my-email-address]' not found: end of file`

I've tried putting my personal gpg in the rc file for those email addresses, and that gets rid of the error message, but the email never gets sent. Is there a setting I'm missing?

**Comment by Ingvix** [comment]
I'm having a similar problem for one of my emails. I tried deleting and re-adding the address. When I inserted the address it gives an error `gpg: error reading key: No public key` but continues the setup as if nothing happened. Still can't send mail.

**Comment by Ingvix** [comment]
Not sure if this is somewhat recent change but apparently it's required for the gpg email to match the one inserted to mw. I don't think this was the case in earlier version of mw as it was working before I had to re-setup some accounts because of some other problems. Probably done due to some security concerns?

Anyway, for me it started working when I generated another key pair with the email I wasn't able to sent messages.

**Comment by LukeSmithxyz** [comment]
Should be fixed. It was requiring a separate gpg private key.

**Comment by tervalentspark** [comment]
Thank you. Do I need to just sync it again for the changes to go into effect?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by LukeSmithxyz** [comment]
Well you should actually just edit the profile config files in `~/.config/mutt/accounts/` and remove the `set pgp_default_key` line and the other few lines in that paragraph/block. Either that or rerun the updated wizard after deleting the account.
