### ISSUE TITLE
Use mw in pure console

### ISSUE THREAD

**Issue by djringjr** [LukeSmithxyz/mutt-wizard#504]
Hello Luke,

I have no idea how difficult this would be to do.

Many blind users love text email programs but mutt and alpine are often difficult for them to use.

mutt-wizard is so easy.

It's possible to use neomutt configured with mutt-wizard but comparing mutt-wizard in terminal with mutt-wizard  OR mw for short.

In terminal a window comes up and asks my gpg password.  I fill it in and neomutt opens.

If I have X windows opan but go to a console and run neomutt, the screen just stays blank.

I went back to the graphic user interface, and there is the password window waiting for my pgp key password.

I had mutt working in console and mutt asked for my gpg password, but it did it in the graphic user interface, but from console I could use Ctrl-c several times and  then mw would ask my log in password, which if I gave it, it would open my mail without error.. If I sent gpg mail, it would ask my password in console.  The only error is when asking for the first password it does so only in terminal not console.

This would be so useful for blind users.

Best wishes,
David

**Comment by niklassc7** [comment]
For the decryption of the GPG keys, `pinentry` is used which has several implementations, some like `pinentry-gtk` use a graphical window for that. If you configure your pinentry to only use the curses version, it should work in only a terminal.

The reason why the screen stayed blank is probably because some other instance of pinentry was running which blocked the pinentry that neomutt tried to call.
