### ISSUE TITLE
Notifications do not work

### ISSUE THREAD

**Issue by g-w1** [LukeSmithxyz/mutt-wizard#537]
I think with the new update, notify-send was removed from the mw script. Is there a way to add it back?

**Comment by se7en-x230** [comment]
I have the same issue. Old setup on desktop has notification and new setup on my laptop doesn't send notification.

**Comment by Kr1ss-XD** [comment]
Here is a link to the [mailsync](https://raw.githubusercontent.com/LukeSmithxyz/mutt-wizard/832b643c48d18959344611544a1dd607eeca4f92/bin/mailsync) script, which has been removed in favor of `mw sync` ~3 months ago. This used to send the notifications.

You could try to put this somewhere into a folder in your `$PATH`, and replace the `mbsync` calls in the neomutt config file with `mailsync`. Be aware though that it has been removed for a number of reasons; see the repository history.

Also, `libnotify` needs to be installed, of course.

**Comment by LukeSmithxyz** [comment]
Yes, this was removed because it was an evermore complicated script that worked on fewer implementations.

As it happens, it's pretty difficult to get it to work universally because to display notifications from a cronjob, you often have to have access to environmental variables and screen information that cronjobs typically do not have.

In the future, I'd like to re-add this feature if a more simple method becomes obvious.

**Comment by se7en-x230** [comment]
Thanks mailsync works fine on your DWM build @LukeSmithxyz and thanks for posting it @Kr1ss-XD
