### ISSUE TITLE
msmtp permissions issue

### ISSUE THREAD

**Issue by christopherisnow** [LukeSmithxyz/mutt-wizard#552]
I have 4 email accounts installed with mw that all work fine. I recently tried setting up a university account and failed, so I manually wrote and/or added to all the relevant config files, using as templates those produced by mw for existing accounts.

In the meantime, I screwed something up and can't send any emails with any accounts with msmtp. At first, I got the error:

```.msmtprc: contains secrets and therefore must have no more than user read/write permissions```

Then I ran `chmod 600 ~/.msmtprc` and got new errors:

```
msmtp: authentication method PLAIN needs a user name
msmtp: could not send mail (account XXX from /home/christopher/.msmtprc)
```

When I manually created and modified the msmtprc, did I fail to enable some permission or password decryption? Sample msmtprc:

```
defaults
auth	on
tls	on
tls_trust_file	/etc/ssl/certs/ca-certificates.crt
logfile	~/.config/msmtp/msmtp.log

account personal
host smtp.anyhost.com
port 587
from cw@anywhere.com
passwordeval "pass mutt-wizard-personal"
```

BTW off topic -- if anyone has general tips about setting up neomutt with a university account, I'm all ears. Certificate handshake issues... the setup works fine on Thunderbird. The IT people here don't support Linux :(

**Comment by f380cedric** [comment]
> `.msmtprc: contains secrets and therefore must have no more than user read/write permissions`

It means you are using `password <secret>` instead of `passwordeval pass <pass-name>`.
I encourage you to store your secret in your password store and not write it down in plaintext in the configuration file (i.e. use `passwordeval pass <pass-name>` instead of `password <secret>`).

> ```
> msmtp: authentication method PLAIN needs a user name
> msmtp: could not send mail (account XXX from /home/christopher/.msmtprc)
> ```
> 
> When I manually created and modified the msmtprc, did I fail to enable some permission or password decryption? Sample msmtprc:
> 
> ```
> defaults
> auth	on
> tls	on
> tls_trust_file	/etc/ssl/certs/ca-certificates.crt
> logfile	~/.config/msmtp/msmtp.log
> 
> account personal
> host smtp.anyhost.com
> port 587
> from cw@anywhere.com
> passwordeval "pass mutt-wizard-personal"
> ```

You need to fill parameter `user <username>` to authentificate, eg:

```
account personal
host smtp.anyhost.com
port 587
from cw@anywhere.com
user <username_to_auth>
passwordeval "pass mutt-wizard-personal"
```

`user` and `from` are not the same thing. The former is use to auth to the server (and it may be equal to your email address, it depends on the server used), the latter is used to fill the from header.

Please, if you want to write msmtprc yourself, have a look at `msmtp (1)` manual.

> BTW off topic -- if anyone has general tips about setting up neomutt with a university account, I'm all ears. Certificate handshake issues... the setup works fine on Thunderbird. The IT people here don't support Linux :(

First, try to set up msmtp. Then [test it](https://wiki.archlinux.org/index.php/msmtp#Test_functionality).

For neomutt (when msmtp is fixed), it depends. Did you configured it as 'offline' (messages are saved on the computer) or as 'online' (no message is saved on the computer)?
If offline, then we use mbsync to handle the IMAP communication.
If online, then we use neomutt to handle the IMAP communication.

It should not be different from another account.

But, wouldn't it be easier to regenerate the configuration using mw?

**Comment by christopherisnow** [comment]
Thanks for your help.

> > `.msmtprc: contains secrets and therefore must have no more than user read/write permissions`
> 
> It means you are using `password <secret>` instead of `passwordeval pass <pass-name>`.
> I encourage you to store your secret in your password store and not write it down in plaintext in the configuration file (i.e. use `passwordeval pass <pass-name>` instead of `password <secret>`).
> 

It was always `passwordeval pass <pass-name>`. I tried it both with and without quotation marks i.e. `pass "mutt-wizard-personal"`. Still no luck. 

> You need to fill parameter `user <username>` to authentificate, eg:
> 
> ```
> account personal
> host smtp.anyhost.com
> port 587
> from cw@anywhere.com
> user <username_to_auth>
> passwordeval "pass mutt-wizard-personal"
> ```

I repeated the email address for `user` but this does not help. FYI for all of my successfully installed accounts (i.e. minus the still uninstalled uni account with a separate user name), no extra user name was necessary. 

> Please, if you want to write msmtprc yourself, have a look at `msmtp (1)` manual.

I will do that. Since normally mw sets up everything perfectly, I figured copying and adjusting those files would do... 

> For neomutt (when msmtp is fixed), it depends. Did you configured it as 'offline' (messages are saved on the computer) or as 'online' (no message is saved on the computer)?
> If offline, then we use mbsync to handle the IMAP communication.
> If online, then we use neomutt to handle the IMAP communication.

offline

> 
> It should not be different from another account.

One would think! But the uni security settings are apparently more complex than my other self-hosted accounts.

> 
> But, wouldn't it be easier to regenerate the configuration using mw?

Indeed! But AFAIK when mw fails to install the account, no files are generated. Correct?

**Comment by f380cedric** [comment]
Which OS are you using?

> > It means you are using `password <secret>` instead of `passwordeval pass <pass-name>`.
> > I encourage you to store your secret in your password store and not write it down in plaintext in the configuration file (i.e. use `passwordeval pass <pass-name>` instead of `password <secret>`).
> 
> It was always `passwordeval pass <pass-name>`. I tried it both with and without quotation marks i.e. `pass "mutt-wizard-personal"`. Still no luck.

Odd, from msmtp source, it prints that out only if `password <secret>` is present in user config ([here](https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=src/conf.c;h=d5ccb7181f92f1d3c94a34856f189e02d6d364c9;hb=HEAD#l2144) and [there](https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=src/conf.c;h=d5ccb7181f92f1d3c94a34856f189e02d6d364c9;hb=HEAD#l1482)).
So it is a bug, or you are not reading the good configuration files. run `msmtp -v` and check which files it reads (the first lines).
To be clear, solving this will not solve all your troubles with your setup, only the part where it cries because permissions are not ok.

>  FYI for all of my successfully installed accounts (i.e. minus the still uninstalled uni account with a separate user name), no extra user name was necessary.

If they were configured using mw, they should have `user <username>`. mw writes down the user in msmtp config file ([here](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/bin/mw#L49)).
If auth is on, then `user username` needs to be set.

BTW, mw put msmtp configuration in `~/.config/msmtp/config`, not in `~/.msmtprc`. If you create the latter, msmtp will not read the former.
Note that `~/.msmtprc` could be symbolic linked to `~/.config/msmtp/config'. Verify with `file ~/.msmtprc`.
If it is not, then msmtp will not read what was written by mw.

> > For neomutt (when msmtp is fixed), it depends. Did you configured it as 'offline' (messages are saved on the computer) or as 'online' (no message is saved on the computer)?
> > If offline, then we use mbsync to handle the IMAP communication.
> > If online, then we use neomutt to handle the IMAP communication.
> 
> offline

Ok, I keep that in mind. But let's try to solve msmtp first.

> > It should not be different from another account.
> 
> One would think! But the uni security settings are apparently more complex than my other self-hosted accounts.

Maybe they are not using port 587 for smtp. Or they do not support STARTTLS.
Try to find out what are the necessary configuration to talk to the smtp server of your uni (which server, which port, TLS or STARTTLS or PLAIN, user as 'email' or just the part before @ or something else, etc.).
You can try to ping a bit using `msmtp --host=<smtp_server> --port=[smtp_port|465|587] --tls=[on|off] --tls-starttls=[on|off]` and see if something relevant comes out.

> > But, wouldn't it be easier to regenerate the configuration using mw?
> 
> Indeed! But AFAIK when mw fails to install the account, no files are generated. Correct?

mw appends new configuration in `~/.config/msmtp/config`, `~/.mbsyncrc` and `~/.config/mutt/muttrc`, test it, and if it fails, remove parts that it appended.
Other configured accounts are untouched. No file are deleted.
Indeed, even on a 1! account that failed, the end results are empty files (but they exist).

**Comment by f380cedric** [comment]
> So it is a bug, or you are not reading the good configuration files. run `msmtp -v` and check which files it reads (the first lines).

Sorry, the correct command is `msmtp --version`. Look for the lines `{System,User} configuration file name`.

**Comment by christopherisnow** [comment]
> Which OS are you using?

Bunsenlabs Lithium, i.e. Debian 10 stable with Openbox.

> 
> > > It means you are using `password <secret>` instead of `passwordeval pass <pass-name>`.
> > > I encourage you to store your secret in your password store and not write it down in plaintext in the configuration file (i.e. use `passwordeval pass <pass-name>` instead of `password <secret>`).
> > 
> > 
> > It was always `passwordeval pass <pass-name>`. I tried it both with and without quotation marks i.e. `pass "mutt-wizard-personal"`. Still no luck.
> 
> Odd, from msmtp source, it prints that out only if `password <secret>` is present in user config ([here](https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=src/conf.c;h=d5ccb7181f92f1d3c94a34856f189e02d6d364c9;hb=HEAD#l2144) and [there](https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=src/conf.c;h=d5ccb7181f92f1d3c94a34856f189e02d6d364c9;hb=HEAD#l1482)).
> So it is a bug, or you are not reading the good configuration files. run `msmtp -v` and check which files it reads (the first lines).
> To be clear, solving this will not solve all your troubles with your setup, only the part where it cries because permissions are not ok.
> 

```
~$ msmtp --version
msmtp version 1.8.3
Platform: x86_64-pc-linux-gnu
TLS/SSL library: GnuTLS
Authentication library: GNU SASL
Supported authentication methods:
plain scram-sha-1 external gssapi cram-md5 digest-md5 login ntlm 
IDN support: enabled
NLS: enabled, LOCALEDIR is /usr/share/locale
Keyring support: none
System configuration file name: /etc/msmtprc
User configuration file name: /home/christopher/.msmtprc
```

> > FYI for all of my successfully installed accounts (i.e. minus the still uninstalled uni account with a separate user name), no extra user name was necessary.
> 
> If they were configured using mw, they should have `user <username>`. mw writes down the user in msmtp config file ([here](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/bin/mw#L49)).
> If auth is on, then `user username` needs to be set.
> 
> BTW, mw put msmtp configuration in `~/.config/msmtp/config`, not in `~/.msmtprc`. If you create the latter, msmtp will not read the former.
> Note that `~/.msmtprc` could be symbolic linked to `~/.config/msmtp/config'. Verify with `file ~/.msmtprc`.
> If it is not, then msmtp will not read what was written by mw.
> 

It seems they are symlinked -- the files are the same although I've never manually edited `~/.config/msmtp/config`.

> Maybe they are not using port 587 for smtp. Or they do not support STARTTLS.
> Try to find out what are the necessary configuration to talk to the smtp server of your uni (which server, which port, TLS or STARTTLS or PLAIN, user as 'email' or just the part before @ or something else, etc.).
> You can try to ping a bit using `msmtp --host=<smtp_server> --port=[smtp_port|465|587] --tls=[on|off] --tls-starttls=[on|off]` and see if something relevant comes out.
> 

Nothing! The process just gets stuck.

> > > But, wouldn't it be easier to regenerate the configuration using mw?
> > 
> > 
> > Indeed! But AFAIK when mw fails to install the account, no files are generated. Correct?
> 
> mw appends new configuration in `~/.config/msmtp/config`, `~/.mbsyncrc` and `~/.config/mutt/muttrc`, test it, and if it fails, remove parts that it appended.
> Other configured accounts are untouched. No file are deleted.
> Indeed, even on a 1! account that failed, the end results are empty files (but they exist).

I tried again and can't find any news files or edits to existing config files anywhere. Could this be a clue to solving the riddles?

**Comment by f380cedric** [comment]
> > Odd, from msmtp source, it prints that out only if `password <secret>` is present in user config ([here](https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=src/conf.c;h=d5ccb7181f92f1d3c94a34856f189e02d6d364c9;hb=HEAD#l2144) and [there](https://git.marlam.de/gitweb/?p=msmtp.git;a=blob;f=src/conf.c;h=d5ccb7181f92f1d3c94a34856f189e02d6d364c9;hb=HEAD#l1482)).
> > So it is a bug, or you are not reading the good configuration files. run `msmtp -v` and check which files it reads (the first lines).
> > To be clear, solving this will not solve all your troubles with your setup, only the part where it cries because permissions are not ok.
> 
> ```
> ~$ msmtp --version
> msmtp version 1.8.3
> Platform: x86_64-pc-linux-gnu
> TLS/SSL library: GnuTLS
> Authentication library: GNU SASL
> Supported authentication methods:
> plain scram-sha-1 external gssapi cram-md5 digest-md5 login ntlm 
> IDN support: enabled
> NLS: enabled, LOCALEDIR is /usr/share/locale
> Keyring support: none
> System configuration file name: /etc/msmtprc
> User configuration file name: /home/christopher/.msmtprc
> ```

Is there any `password <secret>` in  `/etc/msmtprc` (file may not exist) or `/home/christopher/.msmtprc`?
If the answer is no, does it still print `.msmtprc: contains secrets and therefore must have no more than user read/write permissions` (you reported it earlier) when `~/.msmtprc` is 644 (`chmod 644 ~/.msmtprc`)?

> It seems they are symlinked -- the files are the same although I've never manually edited ~/.config/msmtp/config.

You can verify using `file ~/.msmtprc`. It will tell you if it is a symblink or a regular file.
It is expected to be a symblink. mw creates a symlink named `~/.msmtprc` pointing to `~/.config/msmtp/config` on Debian and derivatives.

> > Maybe they are not using port 587 for smtp. Or they do not support STARTTLS.
> > Try to find out what are the necessary configuration to talk to the smtp server of your uni (which server, which port, TLS or STARTTLS or PLAIN, user as 'email' or just the part before @ or something else, etc.).
> > You can try to ping a bit using `msmtp --host=<smtp_server> --port=[smtp_port|465|587] --tls=[on|off] --tls-starttls=[on|off]` and see if something relevant comes out.
> 
> Nothing! The process just gets stuck.
 
My mistake! There is a missing parameter in the command I wrote.
The correct one is : `msmtp --host=<smtp_server> --port=[smtp_port|465|587] --tls=[on|off] --tls-starttls=[on|off] --serverinfo`

> > mw appends new configuration in `~/.config/msmtp/config`, `~/.mbsyncrc` and `~/.config/mutt/muttrc`, test it, and if it fails, remove parts that it appended.
> > Other configured accounts are untouched. No file are deleted.
> > Indeed, even on a 1! account that failed, the end results are empty files (but they exist).
> 
> I tried again and can't find any news files or edits to existing config files anywhere. Could this be a clue to solving the riddles?

What did you try? What did it print?

If you tried something like `mw add uni-account` and it exited with failure,
then it is expected. As I said, if the test fails, it removes all parts related to the account you are trying to configure. But it does not touch configuration related to other configured accounts.

When I said:
> But, wouldn't it be easier to regenerate the configuration using mw?

it was related to your first comment:
> I have 4 email accounts installed with mw that all work fine. I recently tried setting up a university account and failed, so I manually wrote and/or added to all the relevant config files, using as templates those produced by mw for existing accounts.
> 
> In the meantime, I screwed something up and can't send any emails with any accounts with msmtp

I mentioned that because you said you had 4 accounts working before playing around with configuration files.
The easiest way to fix those 4 accounts is to use mw to regenerate sane configuration files (fresh and working start). Then modify them to include your uni account.

**Comment by christopherisnow** [comment]
> Is there any `password <secret>` in `/etc/msmtprc` (file may not exist) or `/home/christopher/.msmtprc`?
> If the answer is no, does it still print `.msmtprc: contains secrets and therefore must have no more than user read/write permissions` (you reported it earlier) when `~/.msmtprc` is 644 (`chmod 644 ~/.msmtprc`)?
> 

Ugh -- yes. In fact there was one account with a normal "password" -- the failing uni -- and that was making it impossible to use any other account! I commented it out, and now at least the accounts that were working before are OK. Sorry for wasting your time on this point...

> > It seems they are symlinked -- the files are the same although I've never manually edited ~/.config/msmtp/config.
> 
> You can verify using `file ~/.msmtprc`. It will tell you if it is a symblink or a regular file.
> It is expected to be a symblink. mw creates a symlink named `~/.msmtprc` pointing to `~/.config/msmtp/config` on Debian and derivatives.
> 

It is, thanks for the tip.

> > > Maybe they are not using port 587 for smtp. Or they do not support STARTTLS.

They are and they do.

> > > Try to find out what are the necessary configuration to talk to the smtp server of your uni (which server, which port, TLS or STARTTLS or PLAIN, user as 'email' or just the part before @ or something else, etc.).

Server name, port 587, STARTTLS, and the username are all given by the uni. This is why I (and the IT folks) are stumped it doesn't work. As mentioned, the very same settings work fine with Thunderbird.

> My mistake! There is a missing parameter in the command I wrote.
> The correct one is : `msmtp --host=<smtp_server> --port=[smtp_port|465|587] --tls=[on|off] --tls-starttls=[on|off] --serverinfo`
> 

It gives a bunch of information, but I'm not sure what exactly would help to install the account beyond the server info listed above. Any ideas?

> If you tried something like `mw add uni-account` and it exited with failure,
> then it is expected. As I said, if the test fails, it removes all parts related to the account you are trying to configure. But it does not touch configuration related to other configured accounts.
> 

Right, the uni account exits with failure. As mentioned, my manual edit (using "password XXX") was what messed things up.

> I mentioned that because you said you had 4 accounts working before playing around with configuration files.
> The easiest way to fix those 4 accounts is to use mw to regenerate sane configuration files (fresh and working start). Then modify them to include your uni account.

Thankfully I don't need to generate new files for the 4 functioning accounts -- whew! -- but I don't know what else to do with respect to the failed uni account. I set up all mbsync, msmtp, and mutt files as best I could according to the mw template, and still get a certificate error message when running mbsync:

```SSL error connecting <mail.XXX.XX> (<ip-address>): unable to get local issuer certificate```

Should I close this issue and open a new one? Is it even relevant to the mw repo, or should I look for help elsewhere? (I appreciate your help, but maybe my problem is too off-topic...)

**Comment by f380cedric** [comment]
> > > > Try to find out what are the necessary configuration to talk to the smtp server of your uni (which server, which port, TLS or STARTTLS or PLAIN, user as 'email' or just the part before @ or something else, etc.).
> 
> Server name, port 587, STARTTLS, and the username are all given by the uni. This is why I (and the IT folks) are stumped it doesn't work. As mentioned, the very same settings work fine with Thunderbird.
> 
> > My mistake! There is a missing parameter in the command I wrote.
> > The correct one is : `msmtp --host=<smtp_server> --port=[smtp_port|465|587] --tls=[on|off] --tls-starttls=[on|off] --serverinfo`
> 
> It gives a bunch of information, but I'm not sure what exactly would help to install the account beyond the server info listed above. Any ideas?

It just means that msmtp was able to interact with the server using that configuration (server + port + protocol).

> I set up all mbsync, msmtp, and mutt files as best I could according to the mw template, and still get a certificate error message when running mbsync:
> 
> `SSL error connecting <mail.XXX.XX> (<ip-address>): unable to get local issuer certificate`

Haaa. It is most likely an issue with your uni server (lol).
I am assuming that your uni's imap is on port 993 (TLS).

So, if you use common ssl online checker, they may say that the certificate cannot be trusted.
Examples:
 - https://certlogik.com/ssl-checker/ → put `imap_uni_server:993` → Check → Trusted | No | (No signatures could be verified because the chain contains only one certificate and it is not self signed.)
 - https://www.sslshopper.com/ssl-checker.html → put `imap_uni_server:993` → Check SSL → The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate
 - https://decoder.link/sslchecker/ → hostname: `imap_uni_server` → port: 993 → CHECK → Trusted: We were unable to verify this certificate; Chain Issues: The chain doesn't contain any intermediate certificates

You can even check locally with openssl:

```
# Incorrect Cert chain
openssl s_client -showcerts -connect imap_uni_server:993 </dev/null

# Correct Cert chain
openssl s_client -showcerts -connect imap.fastmail.com:993 </dev/null
```

You will get something like this for your uni:

```
CONNECTED(00000003)
depth=0 C = REDACTED, ST = REDACTED, L = REDACTED, O = REDACTED, OU = REDACTED, CN = REDACTED
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = REDACTED, ST = REDACTED, L = REDACTED, O = REDACTED, OU = REDACTED, CN = REDACTED,
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:C = REDACTED, ST = REDACTED, L = REDACTED, O = REDACTED, OU = REDACTED, CN = REDACTED
   i:C = REDACTED, ST = REDACTED, L = REDACTED, O = REDACTED, CN = REDACTED
[...]
```

I.e only the end certificate is provided.

While, for imap.fastmail.com, you get:

```
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = AU, ST = Victoria, L = Melbourne, O = FastMail Pty Ltd, CN = *.fastmail.com
verify return:1
---
Certificate chain
 0 s:C = AU, ST = Victoria, L = Melbourne, O = FastMail Pty Ltd, CN = *.fastmail.com
   i:C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
[...]
```

I.e. the full chain is provided.

If I am still right: your uni misconfigured their imap server. They need to provide the fullchain.pem (intermediate + end certificates), not the cert.pem (end certificate).
Not providing the intermediate certificates may work for some browsers and for some mail client because they may implement ways to fetch missing intermediate certificates.
But most will not be able to do it (like openssl, gnutls, and every(?) programs relying on them (eg. curl)).

So, if all my assumptions were right to that point (and if they are, please report to your uni), the only option that you have until your uni fix their servers is to include the missing intermediate certificate.
I can help you for that, but I prefer to wait for your ACK before diging.

> Should I close this issue and open a new one? Is it even relevant to the mw repo, or should I look for help elsewhere? (I appreciate your help, but maybe my problem is too off-topic...)

I am not the project owner. If that person feels that it must be closed for any reason, that person will do it.
We could argue that most of issues in this repo are kinda "off-topic" anyway. Linux/BSD enthusiasts try mw and some need help because GPG/IMAP/TLS/SMTP are complicated and easily misconfigured.

**Comment by christopherisnow** [comment]
> > I set up all mbsync, msmtp, and mutt files as best I could according to the mw template, and still get a certificate error message when running mbsync:
> > `SSL error connecting <mail.XXX.XX> (<ip-address>): unable to get local issuer certificate`
> 
> Haaa. It is most likely an issue with your uni server (lol).
> I am assuming that your uni's imap is on port 993 (TLS).

Right you are, according to https://certlogik.com/ssl-checker ! A little embarassing for the uni IT folks... let's see what they have to say.

> So, if all my assumptions were right to that point (and if they are, please report to your uni), the only option that you have until your uni fix their servers is to include the missing intermediate certificate.
> I can help you for that, but I prefer to wait for your ACK before diging.

That is a very generous offer, doing the work of university employees ;) Back to you soon.

> > Should I close this issue and open a new one? Is it even relevant to the mw repo, or should I look for help elsewhere? (I appreciate your help, but maybe my problem is too off-topic...)
> 
> I am not the project owner. If that person feels that it must be closed for any reason, that person will do it.
> We could argue that most of issues in this repo are kinda "off-topic" anyway. Linux/BSD enthusiasts try mw and some need help because GPG/IMAP/TLS/SMTP are complicated and easily misconfigured.

So much the better, just didn't want to gum up the works here.

**Comment by christopherisnow** [comment]
> > So, if all my assumptions were right to that point (and if they are, please report to your uni), the only option that you have until your uni fix their servers is to include the missing intermediate certificate.
> > I can help you for that, but I prefer to wait for your ACK before diging.

Well, the IT folks are dragging their feet. No idea if or when they will move on this. To save ourselves the trouble of dealing with intermediate certificates, is there any way to accept an untrusted certificate when setting up a mutt account? It seems that's what most people here do with other clients :/

**Comment by f380cedric** [comment]
> To save ourselves the trouble of dealing with intermediate certificates, is there any way to accept an untrusted certificate when setting up a mutt account? It seems that's what most people here do with other clients :/

Yeah. It is not a good idea to add the intermediate certificates in your trusted zone anyway. You should add the end certificate only in your trusted zone.

> I found this http://mutt.sourceforge.net/imap/ (1.2.1.1) but the solution isn't quite clear to me.

Since you want the offline mode, IMAP is not handled by mutt but by mbsync.

First, we need to fetch the certificate:

```sh
# COMPLETE THOSE VAR
export SERVER= #your_uni_imap_server
export CERT_FOLDER= # choose_smth (e.g. ~/.certs, .config/mbsync_certs)
PORT=993 # change that port if uni IMAP TLS is not using 993

# Save Uni IMAP Cert
openssl s_client -connect ${SERVER}:${PORT} -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'| sed -ne '1,/-END CERTIFICATE-/p' > ${CERT_FOLDER}/${SERVER}.pem
```

Then, we need to tell mbsync to trust that certificate, but since mw will restore the old config if the new one failed, it is a bit more complicate:
 - open mw
 - change `CertificateFile $sslcert` on line 59 (defining `mbsync_profile` variable) to `CertificateFile "${CERT_FOLDER}/${SERVER}.pem"`
 - configure your uni mail address (`mw -a ...`) <- this one should succeed 
 - change mw back (`CertificateFile "${CERT_FOLDER}/${SERVER}.pem"` on line 59 (in `mbsync_profile` variable definition) to `CertificateFile $sslcert`)

**Comment by christopherisnow** [comment]
Success! Not quite as planned, though. See below:

> First, we need to fetch the certificate:
> 
> ```shell
> # COMPLETE THOSE VAR
> export SERVER= #your_uni_imap_server
> export CERT_FOLDER= # choose_smth (e.g. ~/.certs, .config/mbsync_certs)
> PORT=993 # change that port if uni IMAP TLS is not using 993
> 
> # Save Uni IMAP Cert
> openssl s_client -connect ${SERVER}:${PORT} -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'| sed -ne '1,/-END CERTIFICATE-/p' > ${CERT_FOLDER}/${SERVER}.pem
> ```

This worked fine, I was able to download the untrusted certificate.

> 
> Then, we need to tell mbsync to trust that certificate, but since mw will restore the old config if the new one failed, it is a bit more complicate:
> 
>     * open mw
> 
>     * change `CertificateFile $sslcert` on line 59 (defining `mbsync_profile` variable) to `CertificateFile "${CERT_FOLDER}/${SERVER}.pem"`
> 
>     * configure your uni mail address (`mw -a ...`) <- this one should succeed
> 
>     * change mw back (`CertificateFile "${CERT_FOLDER}/${SERVER}.pem"` on line 59 (in `mbsync_profile` variable definition) to `CertificateFile $sslcert`)

I still got the same failure notice when trying to add the new account. BUT since I had already manually set up all the config files for the account anyway, all I had to do was specify the certificate in `mbsyncrc` as `CertificateFile ~/.certs/<server.address>.pem` and it's now working fine.

One hopes the uni IT department will get their act together, but at least I have my account working in mutt now... and I know a bit more about how this stuff works for the future.

Many thanks!

**Comment by christopherisnow** [comment]
Reopening this issue as I can no longer use STMP with this infamous uni email account! There was recently a hack and the IT dept apparently made some changes to the certificates. They are no help at all.

After exporting and copying the IMAP certificate to `~./certs`, IMAP works fine.

However after doing the same with the SMTP certificate and adding the line `tls_trust_file ~/.certs/smtp.kug.ac.at.pem` to msmtprc, I get a new error:

`msmtp: cannot set X509 trust file ~/.certs/smtp.kug.ac.at.pem for TLS session: Error while reading`

Have I made a correctable mistake? Or is there a workaround?

**Comment by f380cedric** [comment]
> However after doing the same with the SMTP certificate and adding the line `tls_trust_file ~/.certs/smtp.kug.ac.at.pem` to msmtprc, I get a new error:

`CertificateFile` in mbsync and `tls_trust_file` in msmtp don't exactly do the same thing. The former adds the file to the already loaded CA system store, the latter replaces the loaded CA system store with the file (it is not the issue here, but be aware they are not equivalent).

> `msmtp: cannot set X509 trust file ~/.certs/smtp.kug.ac.at.pem for TLS session: Error while reading`
> 
> Have I made a correctable mistake? Or is there a workaround?

I think there is an error while using the `openssl` command, and since `stderr` is piped to the file, it corrupts it/you don't see the error. You could read it to check if it looks like the `.pem` for mbsync (or run the script without piping/redirecting the output of openssl).

IMO, you use SMTP on 587. Port 587 is a cleartext port (no TLS by default), and you have to upgrade the connection to TLS using STARTTLS. You have to add option `-starttls smtp` to the `openssl` command (disclaimer: I did not test that command):

> ```shell
> # COMPLETE THOSE VAR
> export SERVER= #your_uni_imap_server
> export CERT_FOLDER= # choose_smth (e.g. ~/.certs, .config/mbsync_certs)
> PORT=993 # change that port if uni IMAP TLS is not using 993
> 
> # Save Uni IMAP Cert
> openssl s_client -connect ${SERVER}:${PORT} -starttls smtp -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'| sed -ne '1,/-END CERTIFICATE-/p' > ${CERT_FOLDER}/${SERVER}.pem
> ```

**Comment by f380cedric** [comment]
> `CertificateFile` in mbsync and `tls_trust_file` in msmtp don't exactly do the same thing. The former adds the file to the already loaded CA system store, the latter replaces the loaded CA system store with the file (it is not the issue here, but be aware they are not equivalent).

To get an "equivalent" (adding instead of replacing),
you can use `tls_fingerprint` option in `msmtprc`.
To get the fingerprint, you can use:

```shell
msmtp --host=<smtp_server> --port=[smtp_port|465|587] --tls=on --tls-starttls=[on|off] --serverinfo  --tls-certcheck=off --tls-fingerprint=
```
And add `tls_fingerprint XX:XX:XX:XX:…` in your `msmtprc`.
