### ISSUE TITLE
cron option removed?

### ISSUE THREAD

**Issue by justmeandopensource** [LukeSmithxyz/mutt-wizard#559]
Hi Luke,

Thanks for this wizard. Great work. I always had my own set of scripts to set up this suite of tools. And this made my life a lot easier. I was watching your video about mutt-wizard where you walked through the old version of it where you had mw cron to set the cron. And I don't see that option in the latest version.
Is there a mention of cron anywhere in the latest version or do we have to do it manually in crontab.
```
mw -Y
```
Thanks,
Venkat

**Comment by LukeSmithxyz** [comment]
Yes, the cronjob was removed quite a while ago because it couldn't be universalized properly across systems. Users are expected to add a cronjob themselves if they want one.

If someone can find a simple way of universalizing a cron command that uses all the required environmental variables and displays a new mail message, I would accept that.
