### ISSUE TITLE
Ninxet.email not working with the website config

### ISSUE THREAD

**Issue by Juliaria08** [LukeSmithxyz/mutt-wizard#571]
https://nixnet.email/docs/clients/

**Comment by LukeSmithxyz** [comment]
I suppose you inputted the correct ports and all?

I've never seen someone in `$currentyear` use and STARTTLS IMAP port. I think mutt-wizard assumes an encrypted connection for that.

Maybe Amolith knows what he's doing, but I'm pretty sure that's not an advisable thing to do. STARTTLS is not uncommon for SMTP/receiving unencrypted mail connections, but using it for IMAP I don't think is necessary or a good idea.

**Comment by LukeSmithxyz** [comment]
Looking at the domains.csv file, there is only one other mail site among hundreds who does this aside from nixnet. Protonmail does it as well, but this is because it connected unencrypted to your local machine.

**Comment by Juliaria08** [comment]
Log-on not successful.
It seems that either you inputted the wrong password or server settings, or there are other requirements for your account out of the control of mutt-wizard.

**Comment by Juliaria08** [comment]
Yes it is in the [domains.csv](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/share/domains.csv) file

**Comment by Juliaria08** [comment]
There is any way to make it work?

**Comment by LukeSmithxyz** [comment]
Okay, as I said, I know it's in the file. The issue is that it looks like Nixnet is using unecrypted IMAP ports which may be a safety hazard. I don't want to enable the ability unless I know it's fine to do it.

If you have-to-have-to have it now, run the wizard with the `-f` option and then manually change the `~/.mbsyncrc` file changing the `SSLType` for your account to `STARTTLS`. I think that might do it.

**Comment by Juliaria08** [comment]
I make it now sync's
