### ISSUE TITLE
shared mailbox office 365

### ISSUE THREAD

**Issue by ErickChacon** [LukeSmithxyz/mutt-wizard#575]
Does anyone know how to setup a shared mailbox (office 365) with mw?

**Comment by ErickChacon** [comment]
Just use something like the following:
```
mw -a shared@example.com -u user@example.com
```
and it works perfectly!.

**Comment by ErickChacon** [comment]
Actually, it did not work. It just downloads the mailbox of `user@example.com`.

**Comment by abemposta** [comment]
I've found a way to do this after some tweaking.
You have to configure the shared inbox like this:
```
mw -a shared@example.com -u user@example.com\shared@example.com
```
But it will not work because the ```\``` is skipped in the **mbsync** configuration.

So what I ended up doing was:
```
mw -a shared@example.com -u user@example.com\shared@example.com -f
```
This will force the config generation for the shared mailbox.
After that, you have to manually edit the **mbsync** config file ```.mbsyncrc``` changing the ```User``` value from ```user@example.comshared@example.com``` to ```user@example.com\shared@example.com```

Finally, sync the mail executing ```mw -y shared@example.com``` and everything will work fine.

**Comment by ErickChacon** [comment]
Thank you @abemposta. In that case, I imagine that the following works for you:
```
mw -a shared@example.com -u user@example.com\\shared@example.com
```
In my case, I receive the following 
```
IMAP command 'LOGIN <user> <pass>' returned an error: NO LOGIN failed.
```
I suspect there is a problem with the version of `neomutt` or `isync` I am using.

**Comment by abemposta** [comment]
Hi @ErickChacon. My previous response was not correct.
I tried to get office365 mail to work following my own instructions and failed with the same error.
If you add your account with the following command:
```
mw -a shared@example.com -u user@example.com\\shared@example.com
```
It will have only one backslash on the **mbsync** config file.
For shared mailbox to work you **need** to have **two backslashes** on the `.mbsyncrc` file.
