### ISSUE TITLE
mw won't start without sudo

### ISSUE THREAD

**Issue by user98765446** [LukeSmithxyz/mutt-wizard#576]
Using Manjaro
Installed dependencies and installed with:

git clone https://github.com/LukeSmithxyz/mutt-wizard
cd mutt-wizard
sudo make install

I have run `gpg --full-gen-key` and created a key and I also ran `pass init myname@whyiswmnotworking.cc`

When typing 'mw', as shown in your tutorial, nothing happens.

However, when preceded by 'sudo', I see: 
"`pass` must be installed and initialized to encrypt passwords.
Be sure it is installed and run `pass init <yourgpgemail>`.
If you don't have a GPG public private key pair, run `gpg --full-gen-key` first."

Any thoughts?

**Comment by VolkovIlia** [comment]
Have the same issue with Artix + larbs, mw (add, mod + F8 etc.) not working but mw -Y working well

**Comment by Kr1ss-XD** [comment]
I guess you're following an obsolete tutorial; the tool has been refactored a while ago. You must now tell `mw` what to do by means of commandline arguments. Plain `mw` is suppoosed to do nothing.

Usage is documented in the [README](https://github.com/LukeSmithxyz/mutt-wizard), as well as in the mw(1) man page.

Alas, there's no need to run `mw` (or any of the companion tools) via `sudo` or in the root user context. The error message you got was because `mw` couldn't find a valid password store since it was running as root and your password-db had been initialized in the normal user context.

**Comment by Kr1ss-XD** [comment]
Probably same issue on your end @VolkovIlia - `mw add` is obsolete syntax, a similar functionality is now provided by `mw -a <email@domain> [options ...]`.

Please refer to the README and/or the manual.

**Comment by VolkovIlia** [comment]
And what about cron (time sync) function, did not find anything in man...

**Comment by Kr1ss-XD** [comment]
Cron support has been removed from the project. see [this issue](https://github.com/LukeSmithxyz/mutt-wizard/issues/489).

**Comment by user98765446** [comment]
> @user98765446 I guess you're following an obsolete tutorial; the tool has been refactored a while ago. You must now tell `mw` what to do by means of commandline arguments. Plain `mw` is suppoosed to do nothing.
> 
> Usage is documented in the [README](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/README.md), as well as in the mw(1) man page.
> 
> Alas, there's no need to run `mw` (or any of the companion tools) via `sudo` or in the root user context. The error message you got was because `mw` couldn't find a valid password store since it was running as root and your password-db had been initialized in the normal user context.

@Kr1ss-XD Ah OK. I didn't know. I should have looked at the documentation more closely.
