### ISSUE TITLE
no secret key/ msmtp: cannot read output

### ISSUE THREAD

**Issue by GNUke** [LukeSmithxyz/mutt-wizard#585]
After installing emailwiz on ubuntu 10.4 I am unable to use neomutt send messages. 

I ran gpg keygen, added my email with pass, however when I try to send an email I get the following error:

gpg: decryption failed: No secret key
msmtp: cannot read output of 'pass mw-user@domain.xyz

Further, when I run mw -y user@domain.xyz I get 

C: 0/1  B: 0/0  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0gpg: decryption failed: No secret key
Skipping account user@domain.xyz-remote, password command exited with status 2

I'm abe to send mail with thunderbird.

I am using a user account on the system I created the gpg key under. Any idea why this is happening?

**Comment by LukeSmithxyz** [comment]
What do you get when you run `pass mw-your@email.com`? Is it the correct password?

**Comment by GNUke** [comment]
I get a prompt to unlock my secret key, then it echos the correct password to my mail, I can then send - but not receive - mail though mutt.. 

I am not prompted to enter my gpg key when launching neomutt normally and I can only receive mail if I run  "mw -y your@email.com" (i can both send and receive through thunderbird normally) . I even bound a key to "imap-fetch-mail" to make sure it wasn't just a really long refresh time. 

"pass mw-your@email.com"  seems to "activate" the gpg decryption for mutt but I feel like that is not normal behavior and some kind of permissions issue.

**Comment by LukeSmithxyz** [comment]
Sounds like your system is lacking some basic GPG password entry program like pinentry or it's not being called in mutt, so there are some system setting amiss. You can install `pam-gnupg` as mentioned in the README and that will avoid this problem.

`imap-fetch-mail` has nothing to do with mutt-wizard because mutt does not fetch the mail, `isync` does. Press `o` in mutt-wizard to download mail.
