### ISSUE TITLE
How do I set up mutt-wizard on a cron task or something to automatically run "mw -Y" every so often? 

### ISSUE THREAD

**Issue by justinemter** [LukeSmithxyz/mutt-wizard#603]
I've tried many things, but apparently cronie doesn't have access to "pass" using my users crontab. I tried to alter the "/etc/pam.d/crond" permissions as noted here: https://manintheit.org/unix/configuring-pam-for-crontab/. Unfortunately no luck there. I am using "pam-gnupg" and it works great when manually running "mw -Y".

**Comment by Kr1ss-XD** [comment]
In case you're running a `systemd` box, you might consider a timer/service combination which runs in the user context.

That's how I've solved this on my end. Although the service I use directly calls `mbsync`, not `mw -Y`, but I think that should make no difference.

`~/.config/systemd/user/mailsync.timer` :

```ini
[Unit]
Description=Periodic IMAP - Maildir synchronization
Documentation=man:mbsync(1) man:mw(1) https://github.com/lukesmithxyz/mutt-wizard
After=network-online.target
After=graphical.target

[Timer]
OnStartupSec=30s
OnUnitActiveSec=15m
AccuracySec=1m

[Install]
WantedBy=timers.target
```

`~/.config/systemd/user/mailsync.service` :

```ini
[Unit]
Description=IMAP - Maildir synchronization
Documentation=man:mbsync(1) man:mw(1) https://github.com/lukesmithxyz/mutt-wizard
RequiresMountsFor=/home

[Service]
Type=oneshot
ExecStart=/usr/bin/mbsync -ac /home/%u/.config/mbsyncrc
Nice=18
IOSchedulingClass=idle

[Install]
WantedBy=graphical.target
```

After starting and enabling the timer, e.g. using `systemctl --user enable --now mailsync.timer`, a sync process is launched shortly after the system is up, and every 15 minutes afterwards. Of course the timing can be adjusted to your liking.

I guess there's no harm in changing the `mbsync` call and running `mw -Y` instead.

**Comment by justinemter** [comment]
@Kr1ss-XD Thanks for your thorough reply! Seems like an excellent solution. I implemented it exactly as you illustrated but unfortunately am getting this error: 

`Error: <my-email> is not in the password store.
Dec 25 13:37:27 archlinux mbsync[5948]: Skipping account <my-email>, password command exited with status 1`

Seems similar to my issue when trying this out with cronie. I ran `/usr/bin/mbsync -ac /home/%u/.config/mbsyncrc` just to be sure it works in the terminal, and it definitely does. Seems to still be a pam(?) issue with the password-store being locked for cronie and also for systemd.

**Comment by Kr1ss-XD** [comment]
So cron doesn't seem to be the problem. You could try if adding

```sh
export GPG_TTY=$(tty)
```

to your `~/.profile` solves this after a reboot or logout/login. Also, make sure the [gpg-agent](https://linux.die.net/man/1/gpg-agent) is running - there might be a systemd service and sockets to launch it on demand, depending on your distro, otherwise you might launch it in your startup scripts, see the linked man page.

If that doesn't solve the issue, I'm out of ideas what else could be different here.

**Comment by nicewaffles** [comment]
I was having this problem (or a similar one), and I managed to fix it.
When `cron` or a `systemd` timer runs a job, it's env is not much more than $HOME and $USER. I made a little script that runs by a systemd timer that runs an appropriate `export` on the following variables before running mw -Y:

`PASSWORD_STORE_DIR`
`NOTMUCH_CONFIG`
`MBSYNCRC`
`GPG_TTY` (I added `export GPG_TTY=$(tty)` to my `.zprofile` and just copy/pasted what I got from `env` after logging in)

Note that although you can use `$HOME` while exporting the other variables, stuff like `$XDG_DATA_HOME` or `$XDG_CONFIG_HOME` are not available. Those first three are easy to do since they (should) never change, but I don't think hard-coding `GPG_TTY` is a good idea.

@LukeSmithxyz it may be worth mentioning this in the readme, I imagine many people do not want to manually sync.

**Comment by LukeSmithxyz** [comment]
See #607, I am re-adding this feature.
