### ISSUE TITLE
Authentication failure despite correct password

### ISSUE THREAD

**Issue by salil-sudo** [LukeSmithxyz/mutt-wizard#614]
I am not able to add my email account. I am getting a log in failed message. Before that I was getting authentication failure message. I installed mutt wizard from AUR and I have setup my email using your email wiz. Doing some research on the internet suggests that neomutt is unable to handle long passwords or passwords with special characters. ref: https://github.com/neomutt/neomutt/issues/479
Is this the case with the mutt-wizard as well ?

**Comment by LukeSmithxyz** [comment]
Mutt isn't actually the program authenticating anything in mutt-wizard, unless you are using the online-mail mode. Mbsync logins into to download mail and msmtp logs in to send.

There is a possibility that a change I made last night may've caused your problem since the wizard now tries to test your password with curl. What is your mail provider?

**Comment by PRESFIL** [comment]
Maybe this is because you removed the `-k` option from `curl`'s argv. It was in the original commit to allow an unsecured connection if the provider does not allow the use of a secure one.

**Comment by LukeSmithxyz** [comment]
Well by the way I read the `-k` option, I would anticipate this as being open to sending data over an unencrypted connection. Considering the command has a user password in it, I would assume that is not advisable: wouldn't that make it visible to an ISP?

**Comment by PRESFIL** [comment]
It seemed to me that this is to remove the restriction I do not want to forcibly use an unencrypted connection. The command explicitly specified the protocol `curl -s -k 'imaps://...'`. I wonder how to make sure...

**Comment by LukeSmithxyz** [comment]
Well the curl readme sort of says it backwords for some reason, but on a careful read, it definitely seems like `-k` is for laxing the encryption. That's also why it has an alias `--insecure`.

If this curl command causes and issue, it might be because the OP's mail server goes through some extra DNS settings that makes curling impossible like this. Actually, if I add `-L` it might solve it; I'll go ahead and do so because that will definitely solve a potential problem for someone out there who is redirecting their mail server.

**Comment by PRESFIL** [comment]
> In rare circumstances, you may decide that you still want to communicate with a TLS server even if the certificate verification fails. You then accept the fact that your communication may be subject to Man-In-The-Middle attacks. You lower your guards with the -k or --insecure option.

[source](https://ec.haxx.se/usingcurl/usingcurl-tls#certificate-pinning)

There or otherwise it is also bad...

> Actually, if I add -L it might solve it.

It looks like it's only for HTTP.

**Comment by salil-sudo** [comment]
> Mutt isn't actually the program authenticating anything in mutt-wizard, unless you are using the online-mail mode. Mbsync logins into to download mail and msmtp logs in to send.
> 
> There is a possibility that a change I made last night may've caused your problem since the wizard now tries to test your password with curl. What is your mail provider?

I dont think anything you changed last night made caused this problem. Since I have been having it for a while now. For my email provider, I have my own VPS and I setup my email using your email whiz script. This is what I get. No other error:

`Give your email server's IMAP address (excluding the port number):
mail.salil.cool
Give your email server's SMTP address (excluding the port number):
mail.salil.cool
Enter password for mw-salil@salil.cool:
Retype password for mw-salil@salil.cool:
Log-on not successful.
`

**Comment by LukeSmithxyz** [comment]
> > Mutt isn't actually the program authenticating anything in mutt-wizard, unless you are using the online-mail mode. Mbsync logins into to download mail and msmtp logs in to send.
> > There is a possibility that a change I made last night may've caused your problem since the wizard now tries to test your password with curl. What is your mail provider?
> 
> I dont think anything you changed last night made caused this problem. Since I have been having it for a while now. For my email provider, I have my own VPS and I setup my email using your email whiz script. This is what I get. No other error:
> 
> `Give your email server's IMAP address (excluding the port number): mail.salil.cool Give your email server's SMTP address (excluding the port number): mail.salil.cool Enter password for mw-salil@salil.cool: Retype password for mw-salil@salil.cool: Log-on not successful. `

Okay. First, just in case, depending on if you're going by my old video, nowadays emailwiz will have you login with your whole email address rather than just the username (i.e., don't use the `-u` option with `mw` if you are). Although if you are using an older version, you'll want to run mutt-wizard with `-u yourusername`.

If that isn't the issue, do you have any irregular characters in your password? Could you try temporarily changing it to simple Latin characters and seeing if that aleviates the issue. I suppose it's possible that mbsync might have some kind of issue with some character encoding. I seem to remember that happening before.

**Comment by salil-sudo** [comment]
Oh wow. So I am indeed using an older version (which I got from AUR). Every thing works perfectly fine with the `-u` flag now. On a side note ,I tried having a simple password (without special characters) but it did not work with `mw -a`
