### ISSUE TITLE
Mailbox names missing from sidebar after fresh install

### ISSUE THREAD

**Issue by christopherisnow** [LukeSmithxyz/mutt-wizard#654]
I just installed mw on a new laptop with config files from a previous install. The names of the mailboxes (INBOX, Sent, etc.) are missing from the lefthand sidebar of all accounts in Neomutt. Number of total and unread messages shows up, and I can navigate with the usual shortcuts. All works well except for this weird glitch.

Any idea what's up? Was there a relevant recent change in the source code?

**Comment by LukeSmithxyz** [comment]
Only thing I can immediately think of is that since neomutt
automatically prunes mailbox names, it might be doing something weird if
the server has weird extra text in the names.

Add this to your muttrc and see what it does:

set sidebar_format = '%B%?F? [%F]?%* %?N?%N/? %?S?%S?'

(specifically, this uses %B instead of %D as the mailbox title)

All of this might also be due to you having an older version of neomutt
installed.

**Comment by christopherisnow** [comment]
> set sidebar_format = '%B%?F? [%F]?%* %?N?%N/? %?S?%S?'

Yep that fixed it, thank you kindly.

For the record, neomutt itself was freshly installed, I only copied the old config files.

**Comment by christopherisnow** [comment]
FYI while inspecting  /usr/local/share/mutt-wizard/mutt-wizard.muttrc  I found the culprit on ln. 85:

```
set sidebar_format = '%D%?F? [%F]?%* %?N?%N/? %?S?%S?'
```

The first term should be `%B%` -- no?
