### ISSUE TITLE
mw dont work correct i think

### ISSUE THREAD

**Issue by nevermore2k** [LukeSmithxyz/mutt-wizard#657]
mw -a (my-mail)           
First run `pass init <yourgpgemail>` to set up a password archive.
(If you don't already have a GPG key pair, first run `gpg --full-generate-key`.)

thats all  what happens, i generated the key. should something else happens there ?  

i am on manjaro

**Comment by Kr1ss-XD** [comment]
It needs an encrypted password store, which you must prepare beforehand.

Just do what it tells you, and run the command again once your password archive is ready.

If you've build the wizard via `make`, you'll need to make sure that `pass` is installed, along with the other dependencies. Those are described in the [README](https://github.com/LukeSmithxyz/mutt-wizard#dependencies). (This doesn't apply if you've installed the AUR package, since it pulls in the dependencies automatically.)
