### ISSUE TITLE
mailsync fails in root and in cron

### ISSUE THREAD

**Issue by silasanderson** [LukeSmithxyz/mutt-wizard#683]
when i run mailsync as root i get
```
t480# mailsync
awk: fatal: cannot open file `/root/.mbsyncrc' for reading: No such file or directory
touch: cannot touch '/root/.config/mutt/.mailsynclastrun': No such file or directory
```
otherwise mailsync works fine

**Comment by Kr1ss-XD** [comment]
Looks like you've set up your mail account(s) in a user context other than root. If so, this is expected behavior, since each user has their own configuration, and thus their own email setup.

Out of interest - why would you want to run `mailsync` as root, anyways ?

From a security perspective, I'd recommend to not run _anything_ as root that doesn't need system access, _especially_ if it accesses the internet.

**Comment by silasanderson** [comment]
well i was an idiot. i forgot to start the cronie.service. thanks anyway!

**Comment by Kr1ss-XD** [comment]
NP, glad you could sort it out.
