### ISSUE TITLE
how do i read html mail?

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/mutt-wizard#697]
hey luke, I recently recieved some html email, and it's like i'm viewing it's source code in mutt-wizard ... I have lynx installed and all other dependancies ... what am i missing?

[screenshot](https://0x0.st/-by-.png)

**Comment by Kr1ss-XD** [comment]
I _think_ you're not missing anything here, since this might be an issue with the message itself.

I do experience that sometimes, too, but in these cases it's really the fault of the sender (or their email client), because the html parts of the email are marked with a MIME type of `text/plain`.

Messages/attachments with a `text/html` MIME type should be correctly piped to the browser, while `text/plain` is sent to the pager directly. You can get an overview of all attachments by typing `l` in the pager, after opening an email. If `attach_format` is set to the default, the list will display their types.

**Comment by LukeSmithxyz** [comment]
Yeah, I would guess this is just whoever is sending your mail not knowing how to properly mark mime type or by your system somehow missing it.
