### ISSUE TITLE
add support for tutanota email

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/mutt-wizard#776]
tutanota mail is a encrypted email service similar to protonmail, with better security, could it be possible to add support for it please?

**Comment by LukeSmithxyz** [comment]
No, in fact, I'm more thinking about abandoning Protonmail "compatibility" since it always seems to be finicky. Tutanota doesn't even have a "bridge" thing like Protonmail, so this would be totally impossible.

I advise against using either service if you have the impression that they are more secure. You will also have to deal with lack of compatibility since they are not really exactly the same as "email" on IMAP/SMTP. (They are good for burner mails.)
