### ISSUE TITLE
mbsync

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/mutt-wizard#810]
when I run mbsync -a I keep getting  `Cannot open config file '~/.mbsyncrc': No such file or directory ` isn't the .mbsyncrc auto generated file? whats going on here?

**Comment by clockworkpc** [comment]
> when I run mbsync -a I keep getting `Cannot open config file '~/.mbsyncrc': No such file or directory ` isn't the .mbsyncrc auto generated file? whats going on here?

Same problem here.  I expected `mw` to generate `~/.mbsyncrc` if none exists.
I'm on a brand new installation of LARBS.

**Comment by LukeSmithxyz** [comment]
The generated mbsync configuration file is in ~/.config/mbsync.

Modern versions of mbsync will be able to read this out of the box, but it's possible that for some distros, you need to make a link to that at ~/.mbsyncrc

What distributions are you using? Note that the mw script should automatically create the required link if you are running Debian or Ubuntu, but this link should not be required in Arch-based distributions since they use the most recent versions of mbsync.

**Comment by LukeSmithxyz** [comment]
Actually I'll add that all you should have to run is:

```
ln -s ~/.config/mbsync/config ~/.mbsyncrc
```

But I'm interested why this wasn't done automatically by the script if you are on a Debian distro.

**Comment by focus85** [comment]
Thanks Luke 

> Actually I'll add that all you should have to run is:
> 
> ```
> ln -s ~/.config/mbsync/config ~/.mbsyncrc
> ```
> 
> But I'm interested why this wasn't done automatically by the script if you are on a Debian distro.

Thanks Luke this fixed the issue!! for your question i am on Artix and did a clean install of LARBS and mw.

**Comment by clockworkpc** [comment]
`mutt-wizard` did not generate a file for me at `~/.config/mbsync/config` or anywhere else.
I don't have anything set up and am willing to go nuclear at this point.
What do I have to do to completely uninstall and re-install everything to do with `mutt-wizard` and `neomutt`, and then start over again?

**Comment by engjpacheco** [comment]
Is normal that mw generates an empty config file in mbsync folder? Cause mine was empty so I Cant do mbsync -a, any suggestions?
