### ISSUE TITLE
Source color scheme from a separate file

### ISSUE THREAD

**Issue by petergun6666** [LukeSmithxyz/mutt-wizard#819]
Would you consider refactoring `mutt-wizard.muttrc` and pull out the color scheme into a separate file that is then sourced from the users `muttrc`?

Advantages: 
- the user can create their own, more minimal color scheme, without having to override each and every color-spec to set it back to default. 
- Multiple schemes could be included in the distribution more easily and swapped by sourcing a different file from muttrc.

**Comment by LukeSmithxyz** [comment]
Good idea. I think I'll make this change.

**Comment by LukeSmithxyz** [comment]
Okay, I've tried to do this in a sensible way, but there is a big issue: backwards compatibility. Most people already using this via package manager have a call to the general `mutt-wizard.conf` file. If I split it, they all lose colors.

I was going to separate the files anyway and call them all from the `mutt-wizard.muttrc` file, which would indeed be backwards compatible, but since that's a system file, editing it is just as niche as if we didn't have separate files.

So I am not going to change this now until the next total refactor that moves everything around and breaks everything anyway. The solution now is to copy the mw.muttrc, put it in your home dir with edits and call that instead.
