### ISSUE TITLE
mails fail to synchronize

### ISSUE THREAD

**Issue by leannejdong** [LukeSmithxyz/mutt-wizard#821]
Hi,
Mail synchronization does not seem to work. It worked once yesterday but not thereafter.
I tried
`mw -t 2` 
and saw `Adding automatic mailsync every 2 minutes...`
My `cron -l` shows                                                                                                               ✔ 
`*/2 * * * * /usr/local/bin/mailsync`

**Comment by Eklektisk** [comment]
Can you run `mailsync` in your terminal and paste the results here? You can black out any website names or IP addresses if you want, but note the port it's connecting to.

Are you trying to read mail from a self-hosted mail server (or from your VPS), or are you using an external service (ie. google or protonmail)?

Did you just setup mutt-wizard the day before posting this, or has it been working/running for a longer period of time?

**Comment by leannejdong** [comment]
> Can you run mailsync in your terminal and paste the results here?
mailsync                                                                                                                                                                      ✔ 
C: 1/1  B: 20/20  F: +0/0 *0/0 #0/0  N: +13/13 *0/0 #0/0
Processed 13 total files in almost no time.
Added 7 new messages to the database.
> You can black out any website names or IP addresses if you want, but note the port it's connecting to.
Not too sure what to act...
> Are you trying to read mail from a self-hosted mail server (or from your VPS), or are you using an external service (ie. google or protonmail)?
gmail
> Did you just setup mutt-wizard the day before posting this, or has it been working/running for a longer period of time?
A few days

Thanks! I just need a way to have to auto synchronize rather than I manually mailsync...

**Comment by Eklektisk** [comment]
Alright, so at least mailsync is fetching mail properly. As a warning for the future, you might want to increase the time between checks to 10+ minutes, otherwise Google might block mailsync from accessing your account over IMAP/POP3 (had this happen to me with a different mail reader, was a pain to unblock it).

Is cron working? Assuming your system uses systemd and cronie, check if `systemctl status cronie.service` says the service is active/running. You'll have to modify this command if you use a different init system and/or cron implementation. You can also check if cron is working by trying to create a file in /tmp from your crontab.

Just to verify, is mailsync located or sym-linked at `/usr/local/bin/mailsync`, or is it somewhere else?

**Comment by Eklektisk** [comment]
Did some testing on my machine, ran into the same issue when I removed the `DISPLAY` variable from the top of my crontab. Try setting the display variable before you call mailsync (ie. `*/2 * * * * DISPLAY=:0 /usr/local/bin/mailsync`, assuming `echo "$DISPLAY"` returned `:0`).

**Comment by nakrule** [comment]
I have the same issue with macOS. mailsync works fine when I run it manually, but nothing happened with a cronjob (cron ain't the problem, works fine for other tasks).

**Comment by OleBialas** [comment]
I had the same problem. It seems that in my case, the issue was that I installed cronie but did not start it.
`systemctl enable cronie.service` and `systemctl start cronie.service` fixed the issue
