### ISSUE TITLE
Neomutt opens text/html with emacs and not firefox

### ISSUE THREAD

**Issue by vlashada** [LukeSmithxyz/mutt-wizard#860]
I sometimes get email which are intended to be viewed as html. When I press `l` when reading the mail to view the attachments, and then press enter while hovering the `text/html`, it opens the html in emacs and not in firefox. I have set `text/html` to open with firefox from xdg-open. When I save the file locally, and run `file` on it, I get the following output:

```
❯ file nice.html
nice.html: Unicode text, UTF-8 text, with very long lines (626)
```

which I guess means that linux thinks it is a normal file (it does not contain doctype nor html tags). How can I make neomutt always open files tagged with `text/html` with firefox?

**Comment by LukeSmithxyz** [comment]
This is really the fault of whoever is sending you HTML-like email not properly detectable as HTML. This happens because some people send mail is HTML markup without, as you say, doctypes and other things.

There's nothing I can do about this other than chiding whoever is sending you this mail or totally rewrite or replace `file` to have more liberal triggers for what makes a file HTML.
