### ISSUE TITLE
Question, feature request?

### ISSUE THREAD

**Issue by badlandz** [LukeSmithxyz/mutt-wizard#867]
Yea, I know, ignore this, but worth a shot.. googled for other solutions, maybe someone could point me in the right direction (meanwhile I'm going to just do it with mutt-wizzard and the instructions). But...

Is there any way to just import a thunderbird profile for use in neomutt, just like muttwizard --import PATH/TO/PROF --format=thunderbird or something? With multiple accounts set up, it would just make life so much easier. :-) But... Ah, just mark this "closed" with "not interested" and I won't mind. Worth a shot.

**Comment by LukeSmithxyz** [comment]
I've never looked into how Thunderbird actually stores their account profiles. Since it's Mozilla, I'm assuming it's done in the most annoying and non-generalizable way, probably across multiple files with randomly-generated names.

Either way, I don't think it's a good idea to add this. If Thunderbird account information is easily parsed, someone could make a file line script that inputs the required info into a `mw` command with command-line options. I'd rather not build this into the script proper because then the new issue is adding compatibility with more and more other clients.
