### ISSUE TITLE
Cannot open links with firefox

### ISSUE THREAD

**Issue by rldmt** [LukeSmithxyz/mutt-wizard#873]
Hi,
I have a gmail account and wanted to use this wizard to set it up on my machine. For the most part it is working well except for the syncing issue and opening links with the browser.
When I press CTRL + B a list of links is shown from there lynx opens the links. I wanted to open links with firefox so I changed `/etc/urlview/url_handler.sh` , more specific this line:
```
https_prgs="/usr/X11R6/bin/netscape:XW /usr/bin/lynx:XT /usr/bin/firefox:XW"
```
It only opens the links that start with https. Is there a more elegant way to solve this?

**Comment by LukeSmithxyz** [comment]
This is a question for urlview people. The fact that this is even still in this repository is leftover from four years or so ago since I've moved on to link-handling within the terminal emulator, which I might go ahead and remove since links probably should be done by the terminal emulator and I think most users of this probably do just that.
