### ISSUE TITLE
neomutt via mutt-wizard: admin account works, regular user account not working

### ISSUE THREAD

**Issue by MarkLeakos** [LukeSmithxyz/mutt-wizard#901]
I am on Fedora 37 on a 2015 macbook pro (macos wiped - linux only); I have an admin user (markleakos) and a regular user (doc_mac). I have a gmail account which works great on the admin account but when I run this from the regular user I get an error: 
~]$ mw -y markleakos@gmail.com
```
C: 0/1  B: 0/0  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Maildir error: cannot open store '/home/markleakos/.local/share/mail/markleakos@gmail.com/'
C: 1/1  B: 0/0  F: +0/0 *0/0 #0/0  N: +0/0 *0/0 #0/0
Error: Cannot open database at /home/markleakos/.local/share/mail: Permission denied.
```
I think that mutt-wizard should be looking in /home/**doc_mac**/.local/share/mail (which does exist) . I installed mutt-wizard from the admin account but I would like to be able to use it from a regular user account. How do I correct this?

Thanks,
Mark

(.00106 btc sent to bc1qacqfp36ffv9mafechmvk8f6r8qy4tual6rcm9p)

**Comment by MarkLeakos** [comment]
Thanks for your reply.

I don't want to use mutt on my admin account but since the install required
'sudo' I had to do it that way I thought.

Indeed, I would like to never have to go into my admin account. But some
internal workings of mutt-wizard is looking into that path
/home/markleakos/.local/share/mail
instead of /home/doc_mac/.local/share/mail
I was hoping to change that behavior if possible.

**Comment by KebabLord** [comment]
personally i would create a clean setup if accidentally installed the script as root.
In order to have a clean install, i would first delete my mailboxes one by one using `mw -d mail@address.com`
then on repo folder i would perform a `sudo make uninstall`
then `rm -rf ~/.password-store /home/markleakos/.local/share/mail ~/.config/mutt`

after cleaning everything now it's good to `make install` on repo folder.

**Comment by MarkLeakos** [comment]
Thank you very much for your help. I appreciate it.
