### ISSUE TITLE
utf-7 encoding error

### ISSUE THREAD

**Issue by plokid** [LukeSmithxyz/mutt-wizard#903]
the encoding error which has been mentioned in #149 doesn't really solved. `isync` has merged support in main branch, but it doesn't right configured in muttrc.
![图片](https://user-images.githubusercontent.com/72876162/212217380-0e769787-ecc7-4924-bacb-da85d49f87e3.png)
![图片](https://user-images.githubusercontent.com/72876162/212217498-0400de7f-fcc9-4ac3-8b97-3d07c2888bd2.png)
the display in neomutt also show like this
![图片](https://user-images.githubusercontent.com/72876162/212219431-8612c5e4-e0aa-4a02-955a-ff225708e6f3.png)

**Comment by LukeSmithxyz** [comment]
This is an isync issue. Not a mutt-wizard issue.

**Comment by fromSmolsoft** [comment]
Sorry for bumping old thread. I've just dealt with the issue as well and thought to sum up solution for future users. It seems to be a reoccurring problem. 

It's caused by auto generated `mailboxes` option in `*/.config/mutt/accounts/...@...muttrc` .

Fixing required removing malformed dirs in following locations
1.  `*/.config/mutt/accounts/*.muttrc` ,  inside `mailboxes ...`
2. `.local/share/mail/**/*`  local mails storage (each subdir includes cur,new,tmp)
3. server if you managed to synchronize malformed maildirs
