### ISSUE TITLE
64-bit encoded Subject strings

### ISSUE THREAD

**Issue by TheChymera** [LukeSmithxyz/mutt-wizard#910]
After the last uptate ( 17bb517c391282aa7a384cd713e47ce004680b59 though it might be unrelated), I notice a bunch of emails which in neomutt look fine, but both in the notification boxes and looking at the mail files, have undecoded base64 values.

e.g.:

```
Subject: =?UTF-8?B?SG...gb24g?=
```

I can decode them with `base64 -d` manually by stripping the leading and tail characters, but these are also broken up over lines in chunks... Any ideas how this could be done more easily?

**Comment by LukeSmithxyz** [comment]
I replaced the awk/perl abomination that extracted subjects with a simple sed line, but it can't automatically decode other formatting. I'll revise.

I also notice it has an issue when mails come with multi-line subjects. That should be an easier fix.

**Comment by fabian-thomas** [comment]
I researched a little bit how we could solve this and found that there are multiple packages that could do this decoding for us:
- the `mu view` command from the mu package. This is what I currently use to fix the issue. See commit 1b8cda214705a62af80762db47c1a52a1bdbf108 in my fork. This has the problem of introducing mu as new dependency. (only AUR)
- formail from the procmail package. This one is only in aur too.
- reformime from the maildrop package. Also aur.

What do you think?

**Comment by szero** [comment]
There is `base64` program in coreutils package thats core to arch that does just that, can't it be used?

**Comment by LukeSmithxyz** [comment]
It's not so simple as running the text through `base64`, since there might be individual characters encoded apart from the rest of the subject. E.g. special characters may be wrapped in base64 encoding stuff.

I did write a brief, pure shell function that uses `base64` to decode:

```
decodeline(){
	subject="$1"
	next="${subject##*=\?UTF-8\?B\?}"
	plaintext="${subject%%=\?*}"
	inside="${next%%\?=*}"
	after="${subject#*\?=}"
	printf "%s" "$plaintext"
	echo "$inside" | base64 -d -i
	[ -z "$after" ] && printf "\n" && return
	decodeline "$after"
}
```

The other issue is that some subjects are encoded with quote printable encoding, which is another thing that has to be dealt with.

I might be overlooking a more obvious tool to do this more easily. Obviously mutt can decode subjects, so I'm wondering what tool it uses and if it can be called on the command line.

**Comment by LukeSmithxyz** [comment]
I just brought back the functional, but hacky solutions. If I get bored I will clean them up and optimize them.

**Comment by Shane-XB-Qian** [comment]
seems the 'from' was not very accurate, the notification message (of 'from') looks ugly/huge...
pr #912 raised to refine this a bit.

// subject perhaps there would be multiple-lines, that maybe fine.
